# Quick intro

This is a jupyter notebook for testing / coding. So far, each code block is a separate test; unlike an ordinary notebook, they are not meant to run sequentially.

Let's do MCMC:


Next, running "ei". This started out as a copy of Fritz's code but it's evolved into a working version of ours.

In [2]:
from importlib import reload
import ei_multisample #import *
reload(ei_multisample)
from ei_multisample import *
import cProfile as profile

#ec,erc = legible_values(3,3)
#print(ec,"\n",erc,"\n",ec+erc)
inits = good_inits(0.)
#del inits["ercstar_raw"]
for (nsamps,subn) in [(2,60),(5,60),(2,30),(20,30),(40,5)]:
    ei_multisample.SIM_SIGMA_NU = .001
    #%prun result = trainGuide(nsamps=nsamps,subsample_n=subn)#inits = inits)
    trainGuide(nsamps=nsamps,subsample_n=subn)#inits = inits)
    ei_multisample.SIM_SIGMA_NU = .15
    #%prun result = trainGuide(nsamps=nsamps,subsample_n=subn)#inits = inits)
    trainGuide(nsamps=nsamps,subsample_n=subn)#inits = inits)


base:Yes, I will run. line 5 1 :
Reloading cmult...
Reloading polytopize.
Reloading polytopize.
base:Yes, I will run. line 5 2 :
Reloading polytopize.
exception: [Errno 2] No such file or directory: 'eiresults/scenario_N527_SIG0.001.csv'
alpha beta line 41 1 : tensor([ 0.2000, -0.4800,  0.2800]) tensor([[-0.1500, -0.4300,  0.9400],
        [ 0.0100,  0.4900, -1.2300],
        [ 0.1400, -0.0600,  0.3000]])
ec:tensor([ 0.2000, -0.4800,  0.2800]) line 41 1 :
erc:tensor([[-0.1500, -0.4300,  0.9400],
        [ 0.0100,  0.4900, -1.2300],
        [ 0.1400, -0.0600,  0.3000]]) line 41 1 :
y[0]:tensor([[ 601.,  248., 2031.],
        [ 103.,   78.,   43.],
        [  33.,   21.,   50.]]) line 41 1 :
VS tensor([[ 737.,  347., 2124.],
        [ 734.,  264., 2219.],
        [1103.,  493., 2730.],
        [ 556.,  257., 1509.]])
eiresults/scenario_N527_SIG0.001.csv created
svi.step(... line 41 1 : 0 8.783333333333333 torch.Size([60, 9])
guide:begin line 41 1 : 8.783333333333333 True
types? line 100 

sds: tensor(0.1067, grad_fn=<StdBackward0>) tensor(0.0530, grad_fn=<AddBackward0>) tensor(0.0401, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0175, -0.4369], grad_fn=<SliceBackward>)
epoch 90 loss = 1.72E+07, mean_loss=1.75E+07; sds = {'rc': 0.6344479697350961};
 logitstar = tensor([[-0.1048, -0.8919,  0.9967],
        [ 0.4684, -0.0213, -0.4471],
        [-0.3110, -0.3975,  0.7085]], grad_fn=<AddBackward0>)
sds: tensor(0.0950, grad_fn=<StdBackward0>) tensor(0.0501, grad_fn=<AddBackward0>) tensor(0.0270, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0387, -0.4483], grad_fn=<SliceBackward>)
epoch 100 loss = 1.51E+07, mean_loss=1.74E+07; sds = {'rc': 0.6042249693863404};
 logitstar = tensor([[-0.0840, -0.9523,  1.0363],
        [ 0.5107,  0.0168, -0.5274],
        [-0.3106, -0.4094,  0.7200]], grad_fn=<AddBackward0>)
sds: tensor(0.0993, grad_fn=<StdBackward0>) tensor(0.0478, grad_fn=<AddBackward0>) tensor(0.0235, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0546, -0.4241], gr

sds: tensor(0.0828, grad_fn=<StdBackward0>) tensor(0.0491, grad_fn=<AddBackward0>) tensor(0.0172, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1682, -0.4287], grad_fn=<SliceBackward>)
epoch 280 loss = 1.64E+07, mean_loss=1.69E+07; sds = {'rc': 0.5130956398887897};
 logitstar = tensor([[-0.0507, -1.0401,  1.0908],
        [ 0.4467,  0.2339, -0.6806],
        [ 0.1085, -0.4800,  0.3714]], grad_fn=<AddBackward0>)
sds: tensor(0.0982, grad_fn=<StdBackward0>) tensor(0.0388, grad_fn=<AddBackward0>) tensor(0.0134, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1682, -0.4381], grad_fn=<SliceBackward>)
epoch 290 loss = 1.54E+07, mean_loss=1.69E+07; sds = {'rc': 0.5124141138982516};
 logitstar = tensor([[-0.0527, -1.0446,  1.0973],
        [ 0.4407,  0.2391, -0.6797],
        [ 0.1168, -0.5089,  0.3921]], grad_fn=<AddBackward0>)
sds: tensor(0.0929, grad_fn=<StdBackward0>) tensor(0.0401, grad_fn=<AddBackward0>) tensor(0.0134, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1699, -0.4376], g

epoch 470 loss = 1.87E+07, mean_loss=1.69E+07; sds = {'rc': 0.5100098998072233};
 logitstar = tensor([[-0.0637, -1.0388,  1.1025],
        [ 0.4377,  0.2394, -0.6771],
        [ 0.1895, -0.5631,  0.3736]], grad_fn=<AddBackward0>)
Cutoff reached line 41 1 : 16857063.811263517 16836056.12468571
ec_then_erc_star:
tensor([[ 0.1879, -0.4542],
        [-0.2515, -0.5847],
        [ 0.2499,  0.6936]], grad_fn=<SliceBackward>) (10 elems)
globalpsi:
tensor([0.0278, 0.0293, 0.0391, 0.0368, 0.0183, 0.0168],
       grad_fn=<SliceBackward>) (10 elems)
logsdrcstar:
-0.6733251420654518
precinctpsi:
tensor([0.1050, 0.1045, 0.1043, 0.1054, 0.1054, 0.1000, 0.1054, 0.1054, 0.1054,
        0.1054], grad_fn=<SliceBackward>) (10 elems)
exception: [Errno 2] No such file or directory: 'eiresults/scenario_N527_SIG0.15.csv'
alpha beta line 41 1 : tensor([ 0.2000, -0.4800,  0.2800]) tensor([[-0.1500, -0.4300,  0.9400],
        [ 0.0100,  0.4900, -1.2300],
        [ 0.1400, -0.0600,  0.3000]])
ec:tensor([ 0.2000, 

        [-0.2979, -0.3246,  0.6225]], grad_fn=<AddBackward0>)
sds: tensor(0.1901, grad_fn=<StdBackward0>) tensor(0.1313, grad_fn=<AddBackward0>) tensor(0.1378, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.0470, -0.4031], grad_fn=<SliceBackward>)
epoch 80 loss = 1.83E+07, mean_loss=1.71E+07; sds = {'rc': 0.666976812621088};
 logitstar = tensor([[-0.1783, -0.8081,  0.9864],
        [ 0.3580, -0.0413, -0.3167],
        [-0.3206, -0.3599,  0.6805]], grad_fn=<AddBackward0>)
types? line 100 256
sds: tensor(0.1557, grad_fn=<StdBackward0>) tensor(0.0735, grad_fn=<AddBackward0>) tensor(0.0795, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.0013, -0.4284], grad_fn=<SliceBackward>)
epoch 90 loss = 1.41E+07, mean_loss=1.71E+07; sds = {'rc': 0.6344479697350961};
 logitstar = tensor([[-0.1066, -0.8758,  0.9823],
        [ 0.4537, -0.0263, -0.4274],
        [-0.3510, -0.3830,  0.7340]], grad_fn=<AddBackward0>)
sds: tensor(0.1462, grad_fn=<StdBackward0>) tensor(0.0620, grad_fn=<AddBackward0>) te

        [-0.0797, -0.3922,  0.4719]], grad_fn=<AddBackward0>)
sds: tensor(0.1535, grad_fn=<StdBackward0>) tensor(0.0683, grad_fn=<AddBackward0>) tensor(0.0694, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1017, -0.3964], grad_fn=<SliceBackward>)
epoch 270 loss = 1.73E+07, mean_loss=1.69E+07; sds = {'rc': 0.4948024386105514};
 logitstar = tensor([[-0.0559, -1.0070,  1.0628],
        [ 0.4396,  0.2114, -0.6510],
        [-0.0786, -0.3937,  0.4723]], grad_fn=<AddBackward0>)
sds: tensor(0.1313, grad_fn=<StdBackward0>) tensor(0.0645, grad_fn=<AddBackward0>) tensor(0.0585, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1062, -0.3940], grad_fn=<SliceBackward>)
epoch 280 loss = 1.64E+07, mean_loss=1.69E+07; sds = {'rc': 0.4960590493455108};
 logitstar = tensor([[-0.0605, -1.0126,  1.0730],
        [ 0.4503,  0.2122, -0.6624],
        [-0.0711, -0.3817,  0.4528]], grad_fn=<AddBackward0>)
sds: tensor(0.1311, grad_fn=<StdBackward0>) tensor(0.0713, grad_fn=<AddBackward0>) tensor(0.0654, grad

 ecstar = tensor([ 0.1135, -0.3979], grad_fn=<SliceBackward>)
epoch 460 loss = 1.66E+07, mean_loss=1.69E+07; sds = {'rc': 0.49816507491911516};
 logitstar = tensor([[-0.0632, -1.0060,  1.0692],
        [ 0.4637,  0.2031, -0.6669],
        [-0.0601, -0.3910,  0.4512]], grad_fn=<AddBackward0>)
sds: tensor(0.1410, grad_fn=<StdBackward0>) tensor(0.0691, grad_fn=<AddBackward0>) tensor(0.0624, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1131, -0.4016], grad_fn=<SliceBackward>)
epoch 470 loss = 1.63E+07, mean_loss=1.69E+07; sds = {'rc': 0.4994624395020107};
 logitstar = tensor([[-0.0639, -1.0132,  1.0772],
        [ 0.4658,  0.1912, -0.6570],
        [-0.0624, -0.3828,  0.4452]], grad_fn=<AddBackward0>)
sds: tensor(0.1218, grad_fn=<StdBackward0>) tensor(0.0796, grad_fn=<AddBackward0>) tensor(0.0692, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1126, -0.4000], grad_fn=<SliceBackward>)
epoch 480 loss = 1.84E+07, mean_loss=1.69E+07; sds = {'rc': 0.5004067986399644};
 logitstar = tensor(

 ecstar = tensor([-0.1504, -0.2550], grad_fn=<SliceBackward>)
epoch 50 loss = 3.99E+07, mean_loss=4.08E+07; sds = {'rc': 0.7749164995478804};
 logitstar = tensor([[-0.3262, -0.5100,  0.8362],
        [ 0.1046,  0.0000, -0.1046],
        [-0.2296, -0.2550,  0.4846]], grad_fn=<AddBackward0>)
sds: tensor(0.2145, grad_fn=<StdBackward0>) tensor(0.1429, grad_fn=<AddBackward0>) tensor(0.1579, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.1090, -0.3050], grad_fn=<SliceBackward>)
epoch 60 loss = 3.99E+07, mean_loss=4.10E+07; sds = {'rc': 0.7371233760584002};
 logitstar = tensor([[-0.2563, -0.6100,  0.8663],
        [ 0.1960, -0.0119, -0.1841],
        [-0.2666, -0.2931,  0.5597]], grad_fn=<AddBackward0>)
svi.step(... line 41 64
guide:begin line 41 64
lp:  line 41 64
guide:end line 41 64
model:end line 41 128
sds: tensor(0.1757, grad_fn=<StdBackward0>) tensor(0.0940, grad_fn=<AddBackward0>) tensor(0.1056, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.0788, -0.3550], grad_fn=<SliceBackward>

 ecstar = tensor([ 0.1540, -0.4109], grad_fn=<SliceBackward>)
epoch 240 loss = 4.20E+07, mean_loss=4.21E+07; sds = {'rc': 0.5264005492498942};
 logitstar = tensor([[-0.0548, -1.0433,  1.0981],
        [ 0.4530,  0.2367, -0.6896],
        [ 0.0638, -0.4261,  0.3623]], grad_fn=<AddBackward0>)
sds: tensor(0.0942, grad_fn=<StdBackward0>) tensor(0.0428, grad_fn=<AddBackward0>) tensor(0.0148, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1559, -0.4208], grad_fn=<SliceBackward>)
epoch 250 loss = 4.48E+07, mean_loss=4.21E+07; sds = {'rc': 0.5245475713344242};
 logitstar = tensor([[-0.0540, -1.0461,  1.1002],
        [ 0.4606,  0.2326, -0.6932],
        [ 0.0612, -0.4488,  0.3876]], grad_fn=<AddBackward0>)
Cutoff reached line 41 1 : 42138016.05666193 39327481.26697896
ec_then_erc_star:
tensor([[ 0.1559, -0.4208],
        [-0.2100, -0.6254],
        [ 0.3047,  0.6534]], grad_fn=<SliceBackward>) (10 elems)
globalpsi:
tensor([0.0208, 0.0209, 0.0227, 0.0230, 0.0153, 0.0159],
       grad_fn=<Slic

sds: tensor(0.1817, grad_fn=<StdBackward0>) tensor(0.0976, grad_fn=<AddBackward0>) tensor(0.1090, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.0482, -0.4031], grad_fn=<SliceBackward>)
epoch 80 loss = 3.72E+07, mean_loss=4.32E+07; sds = {'rc': 0.666976812621088};
 logitstar = tensor([[-0.1736, -0.8081,  0.9817],
        [ 0.3568, -0.0594, -0.2973],
        [-0.3279, -0.3417,  0.6696]], grad_fn=<AddBackward0>)
types? line 100 256
sds: tensor(0.1450, grad_fn=<StdBackward0>) tensor(0.0860, grad_fn=<AddBackward0>) tensor(0.0863, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.0048, -0.4128], grad_fn=<SliceBackward>)
epoch 90 loss = 4.22E+07, mean_loss=4.31E+07; sds = {'rc': 0.6344479697350961};
 logitstar = tensor([[-0.1103, -0.8651,  0.9753],
        [ 0.4502, -0.0249, -0.4253],
        [-0.3543, -0.3484,  0.7027]], grad_fn=<AddBackward0>)
sds: tensor(0.1653, grad_fn=<StdBackward0>) tensor(0.0732, grad_fn=<AddBackward0>) tensor(0.0795, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.

        [-0.0714, -0.3578,  0.4292]], grad_fn=<AddBackward0>)
sds: tensor(0.1386, grad_fn=<StdBackward0>) tensor(0.0623, grad_fn=<AddBackward0>) tensor(0.0604, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1093, -0.3990], grad_fn=<SliceBackward>)
epoch 270 loss = 3.80E+07, mean_loss=4.24E+07; sds = {'rc': 0.5096930728702537};
 logitstar = tensor([[-0.0352, -1.0329,  1.0681],
        [ 0.4186,  0.2112, -0.6297],
        [-0.0555, -0.3752,  0.4307]], grad_fn=<AddBackward0>)
sds: tensor(0.1428, grad_fn=<StdBackward0>) tensor(0.0570, grad_fn=<AddBackward0>) tensor(0.0569, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1067, -0.4034], grad_fn=<SliceBackward>)
epoch 280 loss = 4.39E+07, mean_loss=4.24E+07; sds = {'rc': 0.506021921108245};
 logitstar = tensor([[-0.0379, -1.0386,  1.0765],
        [ 0.4030,  0.2119, -0.6149],
        [-0.0449, -0.3836,  0.4286]], grad_fn=<AddBackward0>)
sds: tensor(0.1448, grad_fn=<StdBackward0>) tensor(0.0752, grad_fn=<AddBackward0>) tensor(0.0687, grad_

 ecstar = tensor([ 0.1109, -0.3971], grad_fn=<SliceBackward>)
epoch 460 loss = 4.63E+07, mean_loss=4.25E+07; sds = {'rc': 0.49163292471510567};
 logitstar = tensor([[-0.0583, -1.0095,  1.0678],
        [ 0.4371,  0.1876, -0.6246],
        [-0.0461, -0.3693,  0.4154]], grad_fn=<AddBackward0>)
Cutoff reached line 41 1 : 42524109.53991826 42461258.11117458
ec_then_erc_star:
tensor([[ 0.1109, -0.3971],
        [-0.1692, -0.6124],
        [ 0.3262,  0.5846]], grad_fn=<SliceBackward>) (10 elems)
globalpsi:
tensor([0.0474, 0.0481, 0.0570, 0.0555, 0.0227, 0.0215],
       grad_fn=<SliceBackward>) (10 elems)
logsdrcstar:
-0.7100229289294049
precinctpsi:
tensor([0.1002, 0.1002, 0.1002, 0.1002, 0.1002, 0.1002, 0.1002, 0.1002, 0.1002,
        0.1002], grad_fn=<SliceBackward>) (10 elems)
eiresults/scenario_N527_SIG0.001.csv from file
svi.step(... line 41 1 : 0 17.566666666666666 torch.Size([30, 9])
guide:begin line 41 1 : 17.566666666666666 True
types? line 100 1 : [torch.float64, torch.float64]
typ

sds: tensor(0.1160, grad_fn=<StdBackward0>) tensor(0.0701, grad_fn=<AddBackward0>) tensor(0.0534, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.0086, -0.4344], grad_fn=<SliceBackward>)
epoch 90 loss = 1.94E+07, mean_loss=1.68E+07; sds = {'rc': 0.6344479697350961};
 logitstar = tensor([[-0.1237, -0.8894,  1.0132],
        [ 0.4430, -0.0062, -0.4368],
        [-0.3450, -0.4077,  0.7527]], grad_fn=<AddBackward0>)
sds: tensor(0.0911, grad_fn=<StdBackward0>) tensor(0.0490, grad_fn=<AddBackward0>) tensor(0.0259, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0262, -0.4347], grad_fn=<SliceBackward>)
epoch 100 loss = 1.50E+07, mean_loss=1.69E+07; sds = {'rc': 0.6043878936340865};
 logitstar = tensor([[-0.0809, -0.9336,  1.0145],
        [ 0.5094,  0.0414, -0.5508],
        [-0.3499, -0.4120,  0.7619]], grad_fn=<AddBackward0>)
sds: tensor(0.0991, grad_fn=<StdBackward0>) tensor(0.0443, grad_fn=<AddBackward0>) tensor(0.0277, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0421, -0.4379], gr

lp:  line 41 1 : tensor(-7264189.3956, grad_fn=<AddBackward0>) tensor(1.7181, grad_fn=<AddBackward0>) 760
ps2
guide:end line 41 1 :
model:end line 41 2 :
 ecstar = tensor([-0.0050, -0.0050], grad_fn=<SliceBackward>)
epoch 0 loss = 1.54E+07, mean_loss=1.54E+07; sds = {'rc': 0.9950124793500076};
 logitstar = tensor([[-0.0100, -0.0100,  0.0200],
        [ 0.0000,  0.0000,  0.0000],
        [-0.0050, -0.0050,  0.0100]], grad_fn=<AddBackward0>)
svi.step(... line 41 2 : 1 17.566666666666666 torch.Size([30, 9])
guide:begin line 41 2 : 17.566666666666666 True
types? line 100 4 : [torch.float64, torch.float64]
types? line 100 5 : [torch.float64, torch.float64]
types? line 100 6 : [torch.float64, torch.float64]
model:end line 41 3 :
lp:  line 41 2 : tensor(-6807378.0629, grad_fn=<AddBackward0>) tensor(2.6912, grad_fn=<AddBackward0>) 760
guide:end line 41 2 :
model:end line 41 4 :
svi.step(... line 41 3 : 2 17.566666666666666 torch.Size([30, 9])
guide:begin line 41 3 : 17.566666666666666 True
typ

sds: tensor(0.1522, grad_fn=<StdBackward0>) tensor(0.0692, grad_fn=<AddBackward0>) tensor(0.0705, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0584, -0.4200], grad_fn=<SliceBackward>)
epoch 120 loss = 1.59E+07, mean_loss=1.70E+07; sds = {'rc': 0.5580318985656327};
 logitstar = tensor([[-0.0946, -0.9548,  1.0494],
        [ 0.5307,  0.0895, -0.6202],
        [-0.2610, -0.3946,  0.6556]], grad_fn=<AddBackward0>)
svi.step(... line 41 128
guide:begin line 41 128
lp:  line 41 128
guide:end line 41 128
model:end line 41 256
sds: tensor(0.1664, grad_fn=<StdBackward0>) tensor(0.0862, grad_fn=<AddBackward0>) tensor(0.0818, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0657, -0.4095], grad_fn=<SliceBackward>)
epoch 130 loss = 1.50E+07, mean_loss=1.71E+07; sds = {'rc': 0.5431769172208859};
 logitstar = tensor([[-0.0857, -0.9616,  1.0473],
        [ 0.5046,  0.1298, -0.6345],
        [-0.2220, -0.3968,  0.6188]], grad_fn=<AddBackward0>)
sds: tensor(0.1491, grad_fn=<StdBackward0>) tensor(0.0

lp:  line 41 3 : tensor(-8793033.7507, grad_fn=<AddBackward0>) tensor(2.7944, grad_fn=<AddBackward0>) 760
guide:end line 41 3 :
model:end line 41 6 :
svi.step(... line 41 4 : 3 17.566666666666666 torch.Size([30, 9])
guide:begin line 41 4 : 17.566666666666666 True
types? line 100 10 : [torch.float64, torch.float64]
model:end line 41 7 :
lp:  line 41 4 : tensor(-11427394.0679, grad_fn=<AddBackward0>) tensor(1.5251, grad_fn=<AddBackward0>) 760
guide:end line 41 4 :
model:end line 41 8 :
svi.step(... line 41 5 : 4 17.566666666666666 torch.Size([30, 9])
guide:begin line 41 5 : 17.566666666666666 True
model:end line 41 9 :
lp:  line 41 5 : tensor(-6999221.1361, grad_fn=<AddBackward0>) tensor(3.0995, grad_fn=<AddBackward0>) 760
guide:end line 41 5 :
model:end line 41 10 :
svi.step(... line 41 6 : 5 17.566666666666666 torch.Size([30, 9])
guide:begin line 41 6 : 17.566666666666666 True
types? line 100 16
lp:  line 41 6 : tensor(-8534396.8898, grad_fn=<AddBackward0>) tensor(2.6646, grad_fn=<AddB

epoch 140 loss = 1.78E+08, mean_loss=1.66E+08; sds = {'rc': 0.5408822772184331};
 logitstar = tensor([[-0.0468, -1.0214,  1.0681],
        [ 0.4938,  0.2359, -0.7296],
        [-0.2186, -0.4598,  0.6784]], grad_fn=<AddBackward0>)
sds: tensor(0.0907, grad_fn=<StdBackward0>) tensor(0.0555, grad_fn=<AddBackward0>) tensor(0.0313, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0843, -0.4141], grad_fn=<SliceBackward>)
epoch 150 loss = 2.05E+08, mean_loss=1.67E+08; sds = {'rc': 0.556446048980519};
 logitstar = tensor([[-0.0433, -1.0354,  1.0788],
        [ 0.4807,  0.2446, -0.7253],
        [-0.1844, -0.4514,  0.6358]], grad_fn=<AddBackward0>)
sds: tensor(0.0815, grad_fn=<StdBackward0>) tensor(0.0479, grad_fn=<AddBackward0>) tensor(0.0176, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0892, -0.4048], grad_fn=<SliceBackward>)
epoch 160 loss = 1.68E+08, mean_loss=1.66E+08; sds = {'rc': 0.556004674263697};
 logitstar = tensor([[-0.0507, -1.0431,  1.0938],
        [ 0.4721,  0.2454, -0.7174]

lp:  line 41 7 : tensor(-8374511.0661, grad_fn=<AddBackward0>) tensor(3.7228, grad_fn=<AddBackward0>) 760
guide:end line 41 7 :
svi.step(... line 41 8 : 7 17.566666666666666 torch.Size([30, 9])
guide:begin line 41 8 : 17.566666666666666 True
lp:  line 41 8 : tensor(-7574604.9537, grad_fn=<AddBackward0>) tensor(3.2139, grad_fn=<AddBackward0>) 760
guide:end line 41 8 :
model:end line 41 16
svi.step(... line 41 9 : 8 17.566666666666666 torch.Size([30, 9])
guide:begin line 41 9 : 17.566666666666666 True
lp:  line 41 9 : tensor(-9563259.6604, grad_fn=<AddBackward0>) tensor(3.9976, grad_fn=<AddBackward0>) 760
guide:end line 41 9 :
svi.step(... line 41 10 : 9 17.566666666666666 torch.Size([30, 9])
guide:begin line 41 10 : 17.566666666666666 True
lp:  line 41 10 : tensor(-9795071.7329, grad_fn=<AddBackward0>) tensor(3.2203, grad_fn=<AddBackward0>) 760
guide:end line 41 10 :
types? line 100 32
sds: tensor(0.5167, grad_fn=<StdBackward0>) tensor(0.4835, grad_fn=<AddBackward0>) tensor(0.4900, grad

sds: tensor(0.1514, grad_fn=<StdBackward0>) tensor(0.0929, grad_fn=<AddBackward0>) tensor(0.0899, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0846, -0.4155], grad_fn=<SliceBackward>)
epoch 170 loss = 1.73E+08, mean_loss=1.75E+08; sds = {'rc': 0.5076370117098373};
 logitstar = tensor([[-0.0577, -0.9859,  1.0436],
        [ 0.4616,  0.1764, -0.6380],
        [-0.1499, -0.4371,  0.5870]], grad_fn=<AddBackward0>)
sds: tensor(0.1479, grad_fn=<StdBackward0>) tensor(0.0842, grad_fn=<AddBackward0>) tensor(0.0793, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0808, -0.4137], grad_fn=<SliceBackward>)
epoch 180 loss = 1.55E+08, mean_loss=1.74E+08; sds = {'rc': 0.5087247793052474};
 logitstar = tensor([[-0.0742, -0.9930,  1.0673],
        [ 0.4488,  0.1921, -0.6409],
        [-0.1322, -0.4400,  0.5722]], grad_fn=<AddBackward0>)
sds: tensor(0.1450, grad_fn=<StdBackward0>) tensor(0.0573, grad_fn=<AddBackward0>) tensor(0.0560, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0880, -0.4045], g

ps2
 ecstar = tensor([ 0.1272, -0.3988], grad_fn=<SliceBackward>)
epoch 360 loss = 1.55E+08, mean_loss=1.72E+08; sds = {'rc': 0.5150440511354216};
 logitstar = tensor([[-0.0633, -1.0133,  1.0766],
        [ 0.4558,  0.1977, -0.6535],
        [-0.0109, -0.3807,  0.3916]], grad_fn=<AddBackward0>)
sds: tensor(0.1410, grad_fn=<StdBackward0>) tensor(0.0695, grad_fn=<AddBackward0>) tensor(0.0740, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1193, -0.3976], grad_fn=<SliceBackward>)
epoch 370 loss = 1.97E+08, mean_loss=1.72E+08; sds = {'rc': 0.5101592446217014};
 logitstar = tensor([[-0.0745, -1.0119,  1.0864],
        [ 0.4378,  0.2078, -0.6456],
        [-0.0054, -0.3887,  0.3941]], grad_fn=<AddBackward0>)
sds: tensor(0.1203, grad_fn=<StdBackward0>) tensor(0.0772, grad_fn=<AddBackward0>) tensor(0.0604, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1279, -0.3820], grad_fn=<SliceBackward>)
epoch 380 loss = 1.84E+08, mean_loss=1.73E+08; sds = {'rc': 0.5055732851530415};
 logitstar = tens

epoch 550 loss = 2.24E+08, mean_loss=1.72E+08; sds = {'rc': 0.493009362252519};
 logitstar = tensor([[-0.0656, -1.0172,  1.0828],
        [ 0.4123,  0.2065, -0.6187],
        [ 0.0266, -0.3903,  0.3637]], grad_fn=<AddBackward0>)
sds: tensor(0.1460, grad_fn=<StdBackward0>) tensor(0.0694, grad_fn=<AddBackward0>) tensor(0.0650, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1236, -0.3972], grad_fn=<SliceBackward>)
epoch 560 loss = 1.56E+08, mean_loss=1.71E+08; sds = {'rc': 0.5096030115236018};
 logitstar = tensor([[-0.0586, -1.0196,  1.0783],
        [ 0.4375,  0.2164, -0.6539],
        [-0.0081, -0.3883,  0.3964]], grad_fn=<AddBackward0>)
sds: tensor(0.1215, grad_fn=<StdBackward0>) tensor(0.0930, grad_fn=<AddBackward0>) tensor(0.0754, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1300, -0.4005], grad_fn=<SliceBackward>)
epoch 570 loss = 1.97E+08, mean_loss=1.70E+08; sds = {'rc': 0.5177114308990298};
 logitstar = tensor([[-0.0424, -1.0288,  1.0712],
        [ 0.4577,  0.2103, -0.6679

lp:  line 41 3 : tensor(-6102549.5305, grad_fn=<AddBackward0>) tensor(0.3885, grad_fn=<AddBackward0>) 760
guide:end line 41 3 :
model:end line 41 6 :
svi.step(... line 41 4 : 3 105.4 torch.Size([5, 9])
guide:begin line 41 4 : 105.4 True
types? line 100 10 : [torch.float64, torch.float64]
model:end line 41 7 :
lp:  line 41 4 : tensor(-3912031.0477, grad_fn=<AddBackward0>) tensor(0.8053, grad_fn=<AddBackward0>) 760
guide:end line 41 4 :
model:end line 41 8 :
svi.step(... line 41 5 : 4 105.4 torch.Size([5, 9])
guide:begin line 41 5 : 105.4 True
model:end line 41 9 :
lp:  line 41 5 : tensor(-5146225.5901, grad_fn=<AddBackward0>) tensor(0.7843, grad_fn=<AddBackward0>) 760
guide:end line 41 5 :
model:end line 41 10 :
svi.step(... line 41 6 : 5 105.4 torch.Size([5, 9])
guide:begin line 41 6 : 105.4 True
types? line 100 16
lp:  line 41 6 : tensor(-5133326.9792, grad_fn=<AddBackward0>) tensor(0.6862, grad_fn=<AddBackward0>) 760
guide:end line 41 6 :
svi.step(... line 41 7 : 6 105.4 torch.Size([

sds: tensor(0.1123, grad_fn=<StdBackward0>) tensor(0.0333, grad_fn=<AddBackward0>) tensor(0.0214, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0025, -0.4131], grad_fn=<SliceBackward>)
epoch 150 loss = 5.33E+08, mean_loss=5.98E+08; sds = {'rc': 0.5541861895830968};
 logitstar = tensor([[-0.1052, -0.9426,  1.0478],
        [ 0.5416,  0.1302, -0.6718],
        [-0.4289, -0.4269,  0.8559]], grad_fn=<AddBackward0>)
sds: tensor(0.1315, grad_fn=<StdBackward0>) tensor(0.0541, grad_fn=<AddBackward0>) tensor(0.0312, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0161, -0.4031], grad_fn=<SliceBackward>)
epoch 160 loss = 4.89E+08, mean_loss=5.67E+08; sds = {'rc': 0.5588261567161449};
 logitstar = tensor([[-0.0816, -0.9348,  1.0164],
        [ 0.5631,  0.1501, -0.7132],
        [-0.4333, -0.4245,  0.8578]], grad_fn=<AddBackward0>)
types? line 100 512
sds: tensor(0.0758, grad_fn=<StdBackward0>) tensor(0.0506, grad_fn=<AddBackward0>) tensor(0.0360, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([

sds: tensor(0.0409, grad_fn=<StdBackward0>) tensor(0.0690, grad_fn=<AddBackward0>) tensor(0.0217, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0893, -0.3823], grad_fn=<SliceBackward>)
epoch 340 loss = 3.61E+08, mean_loss=4.01E+08; sds = {'rc': 0.5341732790752713};
 logitstar = tensor([[-0.0414, -1.0493,  1.0907],
        [ 0.4514,  0.2072, -0.6586],
        [-0.1422, -0.3047,  0.4469]], grad_fn=<AddBackward0>)
types? line 100 1024
sds: tensor(0.0813, grad_fn=<StdBackward0>) tensor(0.0463, grad_fn=<AddBackward0>) tensor(0.0121, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1003, -0.3874], grad_fn=<SliceBackward>)
epoch 350 loss = 3.30E+08, mean_loss=3.99E+08; sds = {'rc': 0.5179006098204706};
 logitstar = tensor([[-0.0258, -1.0564,  1.0822],
        [ 0.4519,  0.2008, -0.6526],
        [-0.1253, -0.3065,  0.4318]], grad_fn=<AddBackward0>)
sds: tensor(0.0725, grad_fn=<StdBackward0>) tensor(0.0701, grad_fn=<AddBackward0>) tensor(0.0321, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor(

sds: tensor(0.0557, grad_fn=<StdBackward0>) tensor(0.0570, grad_fn=<AddBackward0>) tensor(0.0200, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1317, -0.3799], grad_fn=<SliceBackward>)
epoch 530 loss = 5.77E+08, mean_loss=3.75E+08; sds = {'rc': 0.5334866935145235};
 logitstar = tensor([[-0.0425, -1.0491,  1.0916],
        [ 0.4598,  0.2425, -0.7023],
        [-0.0222, -0.3330,  0.3552]], grad_fn=<AddBackward0>)
sds: tensor(0.0536, grad_fn=<StdBackward0>) tensor(0.0634, grad_fn=<AddBackward0>) tensor(0.0260, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1277, -0.3794], grad_fn=<SliceBackward>)
epoch 540 loss = 3.04E+08, mean_loss=3.76E+08; sds = {'rc': 0.5276098839460635};
 logitstar = tensor([[-0.0468, -1.0543,  1.1011],
        [ 0.4437,  0.2490, -0.6927],
        [-0.0137, -0.3329,  0.3466]], grad_fn=<AddBackward0>)
sds: tensor(0.0999, grad_fn=<StdBackward0>) tensor(0.0317, grad_fn=<AddBackward0>) tensor(0.0136, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1282, -0.3849], g

epoch 720 loss = 2.77E+08, mean_loss=3.70E+08; sds = {'rc': 0.528579613288727};
 logitstar = tensor([[-0.0701, -1.0531,  1.1232],
        [ 0.4663,  0.2304, -0.6967],
        [ 0.0101, -0.3666,  0.3564]], grad_fn=<AddBackward0>)
sds: tensor(0.0439, grad_fn=<StdBackward0>) tensor(0.0689, grad_fn=<AddBackward0>) tensor(0.0216, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1423, -0.3932], grad_fn=<SliceBackward>)
epoch 730 loss = 5.42E+08, mean_loss=3.72E+08; sds = {'rc': 0.5387078946754237};
 logitstar = tensor([[-0.0559, -1.0358,  1.0917],
        [ 0.4796,  0.2300, -0.7096],
        [ 0.0033, -0.3738,  0.3705]], grad_fn=<AddBackward0>)
sds: tensor(0.0963, grad_fn=<StdBackward0>) tensor(0.0443, grad_fn=<AddBackward0>) tensor(0.0182, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1400, -0.3921], grad_fn=<SliceBackward>)
epoch 740 loss = 2.58E+08, mean_loss=3.70E+08; sds = {'rc': 0.5237712507165359};
 logitstar = tensor([[-0.0605, -1.0330,  1.0935],
        [ 0.4751,  0.2306, -0.7057

sds: tensor(0.0400, grad_fn=<StdBackward0>) tensor(0.0620, grad_fn=<AddBackward0>) tensor(0.0197, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1690, -0.4108], grad_fn=<SliceBackward>)
epoch 920 loss = 3.73E+08, mean_loss=3.56E+08; sds = {'rc': 0.522997955943006};
 logitstar = tensor([[-0.0507, -1.0370,  1.0877],
        [ 0.4447,  0.2411, -0.6858],
        [ 0.1130, -0.4365,  0.3235]], grad_fn=<AddBackward0>)
sds: tensor(0.0573, grad_fn=<StdBackward0>) tensor(0.0715, grad_fn=<AddBackward0>) tensor(0.0249, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1612, -0.4193], grad_fn=<SliceBackward>)
epoch 930 loss = 3.11E+08, mean_loss=3.57E+08; sds = {'rc': 0.5295941236273142};
 logitstar = tensor([[-0.0642, -1.0571,  1.1213],
        [ 0.4530,  0.2392, -0.6922],
        [ 0.0949, -0.4401,  0.3452]], grad_fn=<AddBackward0>)
sds: tensor(0.1215, grad_fn=<StdBackward0>) tensor(0.0261, grad_fn=<AddBackward0>) tensor(0.0100, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1661, -0.4083], gr

 ecstar = tensor([ 0.1538, -0.3886], grad_fn=<SliceBackward>)
epoch 1110 loss = 6.46E+08, mean_loss=3.41E+08; sds = {'rc': 0.5279621166046548};
 logitstar = tensor([[-0.0782, -1.0435,  1.1217],
        [ 0.4603,  0.2159, -0.6761],
        [ 0.0792, -0.3383,  0.2591]], grad_fn=<AddBackward0>)
sds: tensor(0.1244, grad_fn=<StdBackward0>) tensor(0.0306, grad_fn=<AddBackward0>) tensor(0.0095, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1606, -0.3791], grad_fn=<SliceBackward>)
epoch 1120 loss = 3.03E+08, mean_loss=3.34E+08; sds = {'rc': 0.5202108921254639};
 logitstar = tensor([[-0.0617, -1.0176,  1.0794],
        [ 0.4815,  0.2108, -0.6923],
        [ 0.0622, -0.3306,  0.2684]], grad_fn=<AddBackward0>)
sds: tensor(0.1268, grad_fn=<StdBackward0>) tensor(0.0525, grad_fn=<AddBackward0>) tensor(0.0298, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1465, -0.3885], grad_fn=<SliceBackward>)
epoch 1130 loss = 3.39E+08, mean_loss=3.33E+08; sds = {'rc': 0.517369211361436};
 logitstar = tensor

        [ 0.0739, -0.4062,  0.3323]], grad_fn=<AddBackward0>)
sds: tensor(0.0969, grad_fn=<StdBackward0>) tensor(0.0444, grad_fn=<AddBackward0>) tensor(0.0139, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1723, -0.4162], grad_fn=<SliceBackward>)
epoch 1310 loss = 2.86E+08, mean_loss=3.42E+08; sds = {'rc': 0.5254586653035882};
 logitstar = tensor([[-0.0279, -1.0493,  1.0772],
        [ 0.4853,  0.2255, -0.7108],
        [ 0.0595, -0.4249,  0.3654]], grad_fn=<AddBackward0>)
sds: tensor(0.0574, grad_fn=<StdBackward0>) tensor(0.0704, grad_fn=<AddBackward0>) tensor(0.0269, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1647, -0.4184], grad_fn=<SliceBackward>)
epoch 1320 loss = 3.80E+08, mean_loss=3.43E+08; sds = {'rc': 0.5325875739462059};
 logitstar = tensor([[-0.0417, -1.0593,  1.1010],
        [ 0.4713,  0.2431, -0.7144],
        [ 0.0645, -0.4390,  0.3745]], grad_fn=<AddBackward0>)
sds: tensor(0.1413, grad_fn=<StdBackward0>) tensor(0.0320, grad_fn=<AddBackward0>) tensor(0.0145, gr

svi.step(... line 41 1 : 0 105.4 torch.Size([5, 9])
guide:begin line 41 1 : 105.4 True
types? line 100 1 : [torch.float64, torch.float64]
types? line 100 2 : [torch.float64, torch.float64]
types? line 100 3 : [torch.float64, torch.float64]
sds: tensor(0.5962, grad_fn=<StdBackward0>) tensor(0.5825, grad_fn=<AddBackward0>) tensor(0.5776, grad_fn=<StdBackward0>)
model:end line 41 1 :
lp:  line 41 1 : tensor(-6944655.7202, grad_fn=<AddBackward0>) tensor(0.0632, grad_fn=<AddBackward0>) 760
ps2
guide:end line 41 1 :
model:end line 41 2 :
 ecstar = tensor([-0.0050, -0.0050], grad_fn=<SliceBackward>)
epoch 0 loss = 7.55E+08, mean_loss=7.55E+08; sds = {'rc': 0.9950124793500076};
 logitstar = tensor([[-0.0100, -0.0100,  0.0200],
        [ 0.0000,  0.0000,  0.0000],
        [-0.0050, -0.0050,  0.0100]], grad_fn=<AddBackward0>)
svi.step(... line 41 2 : 1 105.4 torch.Size([5, 9])
guide:begin line 41 2 : 105.4 True
types? line 100 4 : [torch.float64, torch.float64]
types? line 100 5 : [torch.float64

        [-0.3491, -0.3998,  0.7489]], grad_fn=<AddBackward0>)
sds: tensor(0.1693, grad_fn=<StdBackward0>) tensor(0.0606, grad_fn=<AddBackward0>) tensor(0.0751, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.0142, -0.3849], grad_fn=<SliceBackward>)
epoch 120 loss = 6.69E+08, mean_loss=6.90E+08; sds = {'rc': 0.5460744284359498};
 logitstar = tensor([[-0.1897, -0.8018,  0.9915],
        [ 0.5143,  0.0466, -0.5609],
        [-0.3672, -0.3995,  0.7667]], grad_fn=<AddBackward0>)
svi.step(... line 41 128
guide:begin line 41 128
lp:  line 41 128
guide:end line 41 128
model:end line 41 256
sds: tensor(0.2231, grad_fn=<StdBackward0>) tensor(0.0448, grad_fn=<AddBackward0>) tensor(0.0673, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0035, -0.3861], grad_fn=<SliceBackward>)
epoch 130 loss = 9.10E+08, mean_loss=6.75E+08; sds = {'rc': 0.5194420643710256};
 logitstar = tensor([[-0.1722, -0.8186,  0.9908],
        [ 0.5510,  0.0461, -0.5972],
        [-0.3683, -0.3859,  0.7542]], grad_fn=<AddBack

        [-0.1256, -0.3876,  0.5132]], grad_fn=<AddBackward0>)
sds: tensor(0.1786, grad_fn=<StdBackward0>) tensor(0.0198, grad_fn=<AddBackward0>) tensor(0.0169, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1009, -0.4205], grad_fn=<SliceBackward>)
epoch 310 loss = 4.21E+08, mean_loss=5.77E+08; sds = {'rc': 0.5108424139297872};
 logitstar = tensor([[-0.0882, -0.9984,  1.0866],
        [ 0.4989,  0.1434, -0.6423],
        [-0.1081, -0.4065,  0.5146]], grad_fn=<AddBackward0>)
sds: tensor(0.1819, grad_fn=<StdBackward0>) tensor(0.0477, grad_fn=<AddBackward0>) tensor(0.0377, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1112, -0.4125], grad_fn=<SliceBackward>)
epoch 320 loss = 3.94E+08, mean_loss=5.66E+08; sds = {'rc': 0.5148112753417385};
 logitstar = tensor([[-0.0700, -0.9816,  1.0515],
        [ 0.5032,  0.1740, -0.6772],
        [-0.0998, -0.4297,  0.5295]], grad_fn=<AddBackward0>)
sds: tensor(0.1828, grad_fn=<StdBackward0>) tensor(0.0527, grad_fn=<AddBackward0>) tensor(0.0514, grad

 ecstar = tensor([ 0.0998, -0.4052], grad_fn=<SliceBackward>)
epoch 500 loss = 5.10E+08, mean_loss=5.13E+08; sds = {'rc': 0.5077879873159327};
 logitstar = tensor([[-0.1020, -0.9667,  1.0686],
        [ 0.4597,  0.1925, -0.6522],
        [-0.0583, -0.4413,  0.4996]], grad_fn=<AddBackward0>)
sds: tensor(0.1358, grad_fn=<StdBackward0>) tensor(0.0389, grad_fn=<AddBackward0>) tensor(0.0370, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0851, -0.4154], grad_fn=<SliceBackward>)
epoch 510 loss = 3.97E+08, mean_loss=5.19E+08; sds = {'rc': 0.5138507071814671};
 logitstar = tensor([[-0.1307, -0.9915,  1.1222],
        [ 0.4365,  0.1816, -0.6181],
        [-0.0504, -0.4364,  0.4868]], grad_fn=<AddBackward0>)
svi.step(... line 41 512
guide:begin line 41 512
lp:  line 41 512
guide:end line 41 512
model:end line 41 1024
sds: tensor(0.1347, grad_fn=<StdBackward0>) tensor(0.0530, grad_fn=<AddBackward0>) tensor(0.0436, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0957, -0.3987], grad_fn=<SliceBa

epoch 690 loss = 4.90E+08, mean_loss=4.92E+08; sds = {'rc': 0.46319450844269655};
 logitstar = tensor([[-0.0824, -0.9868,  1.0692],
        [ 0.3503,  0.1536, -0.5039],
        [ 0.0884, -0.4464,  0.3581]], grad_fn=<AddBackward0>)
sds: tensor(0.1601, grad_fn=<StdBackward0>) tensor(0.1164, grad_fn=<AddBackward0>) tensor(0.1140, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1271, -0.4103], grad_fn=<SliceBackward>)
epoch 700 loss = 4.79E+08, mean_loss=4.89E+08; sds = {'rc': 0.46301377947073935};
 logitstar = tensor([[-0.0671, -0.9528,  1.0199],
        [ 0.3692,  0.1877, -0.5569],
        [ 0.0793, -0.4657,  0.3864]], grad_fn=<AddBackward0>)
sds: tensor(0.1364, grad_fn=<StdBackward0>) tensor(0.0730, grad_fn=<AddBackward0>) tensor(0.0685, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1402, -0.4110], grad_fn=<SliceBackward>)
epoch 710 loss = 4.17E+08, mean_loss=4.82E+08; sds = {'rc': 0.47664738017239033};
 logitstar = tensor([[-0.0545, -0.9541,  1.0086],
        [ 0.4090,  0.1937, -0.

sds: tensor(0.1483, grad_fn=<StdBackward0>) tensor(0.0965, grad_fn=<AddBackward0>) tensor(0.0947, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1340, -0.4417], grad_fn=<SliceBackward>)
epoch 890 loss = 5.19E+08, mean_loss=4.22E+08; sds = {'rc': 0.49304790569884954};
 logitstar = tensor([[-0.0956, -0.9838,  1.0793],
        [ 0.4244,  0.1635, -0.5878],
        [ 0.0731, -0.5048,  0.4317]], grad_fn=<AddBackward0>)
sds: tensor(0.1346, grad_fn=<StdBackward0>) tensor(0.0729, grad_fn=<AddBackward0>) tensor(0.0530, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1430, -0.4223], grad_fn=<SliceBackward>)
epoch 900 loss = 2.96E+08, mean_loss=4.19E+08; sds = {'rc': 0.4922742178140094};
 logitstar = tensor([[-0.0821, -0.9573,  1.0394],
        [ 0.4341,  0.1989, -0.6329],
        [ 0.0771, -0.5084,  0.4313]], grad_fn=<AddBackward0>)
sds: tensor(0.1382, grad_fn=<StdBackward0>) tensor(0.1260, grad_fn=<AddBackward0>) tensor(0.1086, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1475, -0.4139], 

sds: tensor(0.1406, grad_fn=<StdBackward0>) tensor(0.1310, grad_fn=<AddBackward0>) tensor(0.1145, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1437, -0.4342], grad_fn=<SliceBackward>)
epoch 1080 loss = 4.48E+08, mean_loss=3.66E+08; sds = {'rc': 0.49149679272569274};
 logitstar = tensor([[-0.0677, -0.9646,  1.0324],
        [ 0.3954,  0.2277, -0.6232],
        [ 0.1033, -0.5657,  0.4624]], grad_fn=<AddBackward0>)
sds: tensor(0.1345, grad_fn=<StdBackward0>) tensor(0.0321, grad_fn=<AddBackward0>) tensor(0.0325, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1315, -0.4492], grad_fn=<SliceBackward>)
epoch 1090 loss = 2.75E+08, mean_loss=3.67E+08; sds = {'rc': 0.502166642707302};
 logitstar = tensor([[-0.0962, -0.9955,  1.0917],
        [ 0.4018,  0.2059, -0.6077],
        [ 0.0889, -0.5579,  0.4690]], grad_fn=<AddBackward0>)
sds: tensor(0.1346, grad_fn=<StdBackward0>) tensor(0.0621, grad_fn=<AddBackward0>) tensor(0.0568, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1428, -0.4407],

epoch 1270 loss = 4.83E+08, mean_loss=3.47E+08; sds = {'rc': 0.5003724336160892};
 logitstar = tensor([[-0.0696, -1.0259,  1.0955],
        [ 0.4774,  0.1466, -0.6239],
        [ 0.1431, -0.4530,  0.3099]], grad_fn=<AddBackward0>)
sds: tensor(0.0942, grad_fn=<StdBackward0>) tensor(0.1014, grad_fn=<AddBackward0>) tensor(0.0748, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1909, -0.4401], grad_fn=<SliceBackward>)
epoch 1280 loss = 5.86E+08, mean_loss=3.54E+08; sds = {'rc': 0.49967574243529456};
 logitstar = tensor([[-0.0640, -1.0137,  1.0778],
        [ 0.4881,  0.1451, -0.6332],
        [ 0.1487, -0.4518,  0.3031]], grad_fn=<AddBackward0>)
sds: tensor(0.1420, grad_fn=<StdBackward0>) tensor(0.1103, grad_fn=<AddBackward0>) tensor(0.1061, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1853, -0.4602], grad_fn=<SliceBackward>)
epoch 1290 loss = 3.01E+08, mean_loss=3.56E+08; sds = {'rc': 0.494501321806583};
 logitstar = tensor([[-0.0749, -1.0429,  1.1178],
        [ 0.4807,  0.1100, -0.

        [ 0.2283, -0.5503,  0.3220]], grad_fn=<AddBackward0>)
sds: tensor(0.1001, grad_fn=<StdBackward0>) tensor(0.0499, grad_fn=<AddBackward0>) tensor(0.0343, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1780, -0.4536], grad_fn=<SliceBackward>)
epoch 1470 loss = 2.77E+08, mean_loss=3.38E+08; sds = {'rc': 0.4944503429121153};
 logitstar = tensor([[-0.0993, -1.0069,  1.1062],
        [ 0.3949,  0.1963, -0.5912],
        [ 0.2385, -0.5502,  0.3116]], grad_fn=<AddBackward0>)
sds: tensor(0.1866, grad_fn=<StdBackward0>) tensor(0.1041, grad_fn=<AddBackward0>) tensor(0.0947, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.1943, -0.4445], grad_fn=<SliceBackward>)
epoch 1480 loss = 3.01E+08, mean_loss=3.35E+08; sds = {'rc': 0.507771574880506};
 logitstar = tensor([[-0.0755, -1.0007,  1.0762],
        [ 0.4277,  0.2125, -0.6402],
        [ 0.2306, -0.5454,  0.3148]], grad_fn=<AddBackward0>)
sds: tensor(0.1051, grad_fn=<StdBackward0>) tensor(0.0797, grad_fn=<AddBackward0>) tensor(0.0677, gra

        [ 0.2397,  0.6594]], grad_fn=<SliceBackward>) (10 elems)
globalpsi:
tensor([0.9531, 1.2995, 2.6861, 2.6768, 0.6646, 0.6795],
       grad_fn=<SliceBackward>) (10 elems)
logsdrcstar:
-0.6736761794012411
precinctpsi:
tensor([ 1.5401,  4.6551, 13.0518,  6.6301, 37.3312, 30.7982,  9.6820, 37.2323,
        38.4681, 38.4681], grad_fn=<SliceBackward>) (10 elems)



.

.

.



In [2]:
from importlib import reload
import ei_multisample #import *
reload(ei_multisample)
from ei_multisample import *
import cProfile as profile

inits = dict() #good_inits()
#del inits["ercstar_raw"]
#%prun result = trainGuide(inits = inits)

NCparams = EIData.load("NC_Data/NC_2016_statewide_alpha_and_beta.csv")
print(NCparams.alpha + NCparams.beta)
#print("components")
#print(NCparams.alpha)
#
#print(NCparams.beta)
print(SIM_SIGMA_NU)
SIM_SIGMA_NU = 0.001
print(ei_multisample.SIM_SIGMA_NU)
ei_multisample.SIM_SIGMA_NU = .0001
print(ei_multisample.SIM_SIGMA_NU)

base:Yes, I will run. line 5 3 :
Reloading polytopize.
tensor([[ 0.0500, -0.9100,  1.2200],
        [ 0.2100,  0.0100, -0.9500],
        [ 0.3400, -0.5400,  0.5800]])
0.15
0.15
0.0001


# Testing hessian transparency

In [18]:
import torch
ts = torch.tensor
os = torch.ones
zs = torch.zeros
from importlib import reload
import myhessian
reload(myhessian)

t1 = os(2,2,requires_grad=True)
r = torch.sum(t1 * t1 * t1)

h = myhessian.hessian(r,t1)
print("hess",h)
r2 = torch.sum(h * h)
[r3] = torch.autograd.grad(r,t1,create_graph=True,retain_graph=True)
print("d ",r3)
print("Σd ",torch.sum(r3))
[r4] = torch.autograd.grad(torch.sum(r3),t1,create_graph=True,retain_graph=True)
print("dΣdΣd ",torch.autograd.grad(torch.sum(r4),t1,create_graph=True,retain_graph=True))
print(torch.autograd.grad(r2,t1))

hess tensor([[6., 0., 0., 0.],
        [0., 6., 0., 0.],
        [0., 0., 6., 0.],
        [0., 0., 0., 6.]], grad_fn=<CopySlices>)
d  tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
Σd  tensor(12., grad_fn=<SumBackward0>)
dΣdΣd  (tensor([[6., 6.],
        [6., 6.]]),)
(tensor([[72., 72.],
        [72., 72.]]),)


In [4]:
import sys
import hessian

from importlib import reload
import polytopize #import *
reload(polytopize)
from polytopize import *

import tests


Yes, I will run.
Yes, I will run.
ge fail
loc tensor([[ 0.3147],
        [ 2.4440],
        [-4.0535],
        [ 2.2007]])
polytopedLoc tensor([[ 2.1063e-01,  2.1136e-02],
        [ 2.8514e-01, -1.8626e-09],
        [ 3.4959e-01,  9.9957e-02],
        [ 3.5462e-01,  1.1892e-02],
        [ 2.5462e+00,  3.2228e-01]])
ge fail
loc tensor([[-5.8855],
        [-5.2805],
        [ 5.4654],
        [ 0.1889]])
polytopedLoc tensor([[ 2.8885e-01,  1.1871e+00],
        [ 8.5629e-01,  2.0505e+00],
        [ 3.9984e-01, -1.4901e-08],
        [ 9.5542e-01,  1.5538e+00],
        [ 1.0063e+00,  9.9522e-01]])
Reloading cmult...
callable? <bound method TorchDistributionMixin.__call__ of Multinomial()>
callable? <bound method TorchDistributionMixin.__call__ of TorchCMult()>
Sampling multinomial: tensor([1., 2.])
Sampling cm2: tensor([0., 3.])
tensor(5.6022, grad_fn=<NegBackward>) tensor([[112.2500]])


# Test rank1torch (to get yhat from pi,n,v)

In [10]:
from importlib import reload
import rank1torch #import *
reload(rank1torch)
from rank1torch import *

test_solver()

Testing optimize_Q (50 tests): 
R=3, C=5, tolerance=0.001
Oh no! In test 3, Q has some negative entries:
	 trueQ[2][4]=0.00010659269901225343, 
	     Q[2][4]=-0.00021605131041724235
Oh no! In test 5, Q has some negative entries:
	 trueQ[1][4]=0.00011974151857430115, 
	     Q[1][4]=-1.1631345842033625e-06
Oh no! In test 8, Q has some negative entries:
	 trueQ[0][1]=2.882161788875237e-05, 
	     Q[0][1]=-0.0004783869662787765
Oh no! In test 15, Q has some negative entries:
	 trueQ[2][3]=0.0007846675580367446, 
	     Q[2][3]=-6.166117964312434e-05
Oh no! In test 28, Q has some negative entries:
	 trueQ[0][4]=8.13114020274952e-05, 
	     Q[0][4]=-0.00018321917741559446
Oh no! In test 40, Q has some negative entries:
	 trueQ[2][3]=0.00032634526723995805, 
	     Q[2][3]=-0.000617634505033493
Oh no! In test 47, Q has some negative entries:
	 trueQ[2][1]=0.00017936740186996758, 
	     Q[2][1]=-0.00041433278238400817
Oh no! In test 48, Q has some negative entries:
	 trueQ[0][0]=4.52485837740823

## Overview

Most SVI problems in pyro are coded as a model, a generic guide (such as: multivariate Gaussian in all parameters), and specific observations/data (passed as arguments to svi.step). For EI, that's going to be different; the observations are going to be built into the guide function, leaving nothing to include in the "data" argument to svi.step.

That means there is a lot of work for the guide to do. As usual, it must establish reasonable distributional families for the posterior of each of the hyperparameters. But for the latent parameters, the job of the guide is to take a "relative strength" number for each race/candidate/precinct combo, and turn that into a number of votes for each combo, such that those numbers obey all the constraints set by observations. This means that for each precinct (considered separately), the latent guide must:

-Find the "center point" where candidate preference is independent of race.

-Find the "basis vectors" (actually, there are more than enough of them to form a basis) which determine the directions to move in the space.

-For any given set of "relative strengths" which is a distance $d$ in a direction $\theta$, find the first constraint violated when moving in that direction, and the distance $r$ between the origin and that constraint.

-Project the "relative strengths" onto the numbers of votes, by moving $r(1-e^{-d})$ in direction $\theta$.

#### a = zs(2,2,2,2)
a[0,1,1,1] = 2
print(a[1,1])
print(a[0,1])
print(torch.max(a))
print(torch.distributions.exponential.Exponential(ts([1])).sample(4))