# Quick intro

Scratch:


In [8]:
import json
import sys
import pyro

print(pyro.__file__)


print(sys.executable)

/anaconda3/lib/python3.7/site-packages/pyro/__init__.py
/anaconda3/bin/python


Amortizable hierarchical t model:

In [ ]:
from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

#vals = MIDDF35
guidenames = ["amortized_laplace","meanfield","unamortized_laplace"]#,"unamortized_laplace","meanfield",]#,"MLE"]#,"laplace"
if True:

    for aniter in range(10):
        for trueparams in [ndom_norm_params,ndom_fat_params,]:#,tdom_fat_params,tdom_norm_params,]:
            for nsamps,nparticles in [(50,3),(100,1),(50,5),(50,1),]:#(10,1),(10,3),(50,1),(50,3),(100,1),(400,1)]:#(44,5)]:#]:#,
                    for guidename in guidenames:
                        #

                        print(aniter,nparticles,guidenames,trueparams)
                        result = trainGuide(guidename,nparticles,trueparams,
                                            filename="testresults/demoT_2.csv",

                                            subsample_N = nsamps,
                                           name_offset=0)
                        print(aniter,nparticles,guidenames)
                        for line in range(10):
                            print()
                    
else:
    plt.plot([getMLE(.01 + x/100,1.,0,1.) for x in range(500)])
                    

0 3 ['amortized_laplace', 'meanfield', 'unamortized_laplace'] [{'modal_effect': 1.0, 'df': 30.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu30.0.csv from file
400
tensor([ 4.2983,  5.0246, -0.0529,  2.4836])
Sizes: torch.Size([400]) torch.Size([400])
guidename amortized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 30.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 50 8.0
yay 7 fix_m_grad
epoch 0 loss = 1016.3002998630205; mean_loss= 1016.3002998630205; ()
mode_hat tensor(-0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
yay -80
yay -140
yay -200
yay -260
epoch 100 loss = 989.5257201592128; mean_loss= 1020.4372519515316; ()
mode_hat tensor(0.3680, requires_grad=True)
ltscale_hat tensor(-0.5050, requires_grad=True)
ldfraw_hat tensor(0.5052, requires_grad=True)
yay -320
yay -380
yay -440
yay -500
yay -560
epoch 200 loss = 954.1049318710964; mean_loss= 

        -1.6729,  0.8486], grad_fn=<SliceBackward>) (10 elems)
t_part_sigma:
tensor([0.6671, 0.4984, 0.6368, 0.7200, 0.8624, 0.1450, 0.7211, 0.3115, 0.5455,
        0.3219], grad_fn=<SliceBackward>) (10 elems)
0 3 ['amortized_laplace', 'meanfield', 'unamortized_laplace']










0 3 ['amortized_laplace', 'meanfield', 'unamortized_laplace'] [{'modal_effect': 1.0, 'df': 30.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu30.0.csv from file
400
tensor([ 4.2983,  5.0246, -0.0529,  2.4836])
Sizes: torch.Size([400]) torch.Size([400])
guidename unamortized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 30.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 50 8.0
epoch 0 loss = 3983.9284252723055; mean_loss= 3983.9284252723055; ()
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
epoch 100 loss = 1289.903274277846; mean_loss= 2158.12052723951; ()
mode_hat tensor(0.5050, requires_grad=True)

C:\Users\jameson\Anaconda3\lib\site-packages\pyro\poutine\trace_struct.py:231: UserWarning: Encountered NaN: log_prob_sum at site 't_scale_raw'
  warn_if_nan(site["log_prob_sum"], "log_prob_sum at site '{}'".format(name))
C:\Users\jameson\Anaconda3\lib\site-packages\pyro\infer\trace_elbo.py:138: UserWarning: Encountered NaN: loss
  warn_if_nan(loss, "loss")


complaint 9 ldfraw_hat.grad
> c:\users\jameson\dropbox\eipython\eipython\multisitet.py(628)fix_df_grad()
-> if torch.any(torch.isnan(ddfr.grad)):


\
MCMC, etc. 

In [3]:
print("running...")

import sys, os

print(sys.executable)
#print(sys.path)

from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

print("making:")

multisiteMod = createScenario(tdom_fat_params)


running...
/anaconda3/bin/python
Reloading polytopize.
addHess tested
addHess tested
making:
1
testresults/scenario_N44_mu1.0_sigma2.0_nu-1.0.csv from file
44
tensor([32.5364, -3.3454,  3.2929, -2.5415])
{'hessian': tensor([[1., 0., 1.],
        [0., 2., 0.],
        [1., 0., 1.]]), 'logPosterior': 0}


In [13]:
multisiteMod.

SyntaxError: invalid syntax (<ipython-input-13-78d7c46ccca3>, line 1)

In [8]:
maxError = torch.max(errors)
print(float(maxError))

0.27889007329940796
