# Quick intro

Scratch:


In [8]:
import json
import sys
import pyro

print(pyro.__file__)


print(sys.executable)

/anaconda3/lib/python3.7/site-packages/pyro/__init__.py
/anaconda3/bin/python


Amortizable hierarchical t model:

In [ ]:
from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

#vals = MIDDF35
guidenames = ["amortized_laplace","meanfield","unamortized_laplace"]#,"unamortized_laplace","meanfield",]#,"MLE"]#,"laplace"
if True:

    for aniter in range(3):
        for trueparams in [ndom_fat_params,ndom_norm_params]:#,tdom_fat_params,tdom_norm_params,]:
            for nsamps,nparticles in [(10,1),(10,3),(50,1),(50,3),(100,1),(400,1)]:
                    for guidename in guidenames:
                        #

                        print(aniter,nparticles,guidenames,trueparams)
                        result = trainGuide(guidename,nparticles,trueparams,
                                            filename="testresults/demoT_2.csv",

                                            subsample_N = nsamps)
                        print(aniter,nparticles,guidenames)
                        for line in range(10):
                            print()
                    
else:
    plt.plot([getMLE(.01 + x/100,1.,0,1.) for x in range(500)])
                    

0 1 ['amortized_laplace', 'meanfield', 'unamortized_laplace'] [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu3.0.csv from file
400
tensor([-7.9208,  0.5222,  0.8593,  2.3906])
Sizes: torch.Size([400]) torch.Size([400])
guidename amortized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 10 40.0
yay 7 fix_m_grad
epoch 0 loss = 1114.9764868021011;
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(0.0050, requires_grad=True)
ldfraw_hat tensor(-0.0050, requires_grad=True)
yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
yay -80
yay -140
complaint 9 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-771.5305]], grad_fn=<IndexBackward>) tensor([[789.4745]], grad_fn=<IndexBackward>) tensor([[-276.8895]], grad_fn=<IndexBackward>) tensor([[259.0411]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.0957]], grad_fn=<IndexBackward>)
complaint 8 assert approx_eq: tensor([[15

sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 10 40.0
epoch 0 loss = 2072.3795664310455;
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
epoch 100 loss = 1703.8440679311752;
mode_hat tensor(0.5050, requires_grad=True)
ltscale_hat tensor(-0.3304, requires_grad=True)
ldfraw_hat tensor(0.2016, requires_grad=True)
epoch 200 loss = 1163.0583981275558;
mode_hat tensor(1.0050, requires_grad=True)
ltscale_hat tensor(-0.5834, requires_grad=True)
ldfraw_hat tensor(0.3087, requires_grad=True)
epoch 300 loss = 1039.4693734645844;
mode_hat tensor(1.0183, requires_grad=True)
ltscale_hat tensor(-0.8257, requires_grad=True)
ldfraw_hat tensor(0.3863, requires_grad=True)
epoch 400 loss = 1036.214755654335;
mode_hat tensor(1.0276, requires_grad=True)
ltscale_hat tensor(-1.1008, requires_grad=True)
ldfraw_hat tensor(0.4480, requires_grad=True)
epoch 500 loss = 1048.273517

epoch 400 loss = 992.8926900227865;
mode_hat tensor(0.8931, requires_grad=True)
ltscale_hat tensor(-1.3673, requires_grad=True)
ldfraw_hat tensor(0.7600, requires_grad=True)
yay -1220
yay -1280
yay -1340
yay -1400
yay -1460
complaint -280
epoch 500 loss = 1212.1282603740692;
mode_hat tensor(0.9838, requires_grad=True)
ltscale_hat tensor(-1.7219, requires_grad=True)
ldfraw_hat tensor(0.8114, requires_grad=True)
Final mean_losses: 1073.6280764819255
guidename amortized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
globalpsi:
tensor([-4.0672, -3.9105], grad_fn=<SliceBackward>) (10 elems)
latentpsi:
tensor([-4.6052], requires_grad=True)
ldfraw_hat:
0.8114436268806458
ltscale_hat:
-1.7218799591064453
mode_hat:
0.983806312084198
0 3 ['amortized_laplace', 'meanfield', 'unamortized_laplace']










0 3 ['amortized_laplace', 'meanfield', 'unamortized_laplace'] [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu3.0.csv fro

              1.. tensor([[-766.7546]], grad_fn=<IndexBackward>) tensor([[778.4912]], grad_fn=<IndexBackward>) tensor([[-267.3223]], grad_fn=<IndexBackward>) tensor([[255.7760]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.1903]], grad_fn=<IndexBackward>)
complaint 3 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-768.1425]], grad_fn=<IndexBackward>) tensor([[779.8497]], grad_fn=<IndexBackward>) tensor([[-267.0170]], grad_fn=<IndexBackward>) tensor([[255.4306]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.1207]], grad_fn=<IndexBackward>)
complaint 2 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-768.2784]], grad_fn=<IndexBackward>) tensor([[780.3611]], grad_fn=<IndexBackward>) tensor([[-266.5933]], grad_fn=<IndexBackward>) tensor([[255.1094]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.5987]], grad_fn=<IndexBackward>)
complaint 1 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-772.8248]], grad_fn=<IndexBack

        -0.0561,  2.1383], grad_fn=<SliceBackward>) (10 elems)
t_part_sigma:
tensor([0.9521, 0.4758, 0.8781, 0.9984, 0.5650, 0.9104, 1.0012, 0.5246, 0.6280,
        0.5272], grad_fn=<SliceBackward>) (10 elems)
0 1 ['amortized_laplace', 'meanfield', 'unamortized_laplace']










0 1 ['amortized_laplace', 'meanfield', 'unamortized_laplace'] [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu3.0.csv from file
400
tensor([-7.9208,  0.5222,  0.8593,  2.3906])
Sizes: torch.Size([400]) torch.Size([400])
guidename unamortized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 50 8.0
epoch 0 loss = 3341.8650502562523;
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
epoch 100 loss = 1562.6680627465248;
mode_hat tensor(0.5050, requires_grad=True)
ltscale_hat tensor(-0.4764, requires_grad=True)
ldfraw_hat tensor(0

guidename amortized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
globalpsi:
tensor([-4.5535, -4.2508], grad_fn=<SliceBackward>) (10 elems)
latentpsi:
tensor([-4.6052], requires_grad=True)
ldfraw_hat:
-0.3592480719089508
ltscale_hat:
-2.121051073074341
mode_hat:
1.0897966623306274
0 3 ['amortized_laplace', 'meanfield', 'unamortized_laplace']










0 3 ['amortized_laplace', 'meanfield', 'unamortized_laplace'] [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu3.0.csv from file
400
tensor([-7.9208,  0.5222,  0.8593,  2.3906])
Sizes: torch.Size([400]) torch.Size([400])
guidename meanfield
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 50 8.0
epoch 0 loss = 31418.25775653124;
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
epoch 100 loss = 11213.163178265095;
mode_hat tensor(0.3239, 

ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
yay 4 fix_m_grad
yay 1 fix_m_grad
complaint 9 assert approx_eq: tensor([[145],
        [153]]) 
              1.. tensor([[-851.9849],
        [-755.9136]], grad_fn=<IndexBackward>) tensor([[879.8873],
        [760.7631]], grad_fn=<IndexBackward>) tensor([[-311.2720],
        [-270.2596]], grad_fn=<IndexBackward>) tensor([[283.4231],
        [265.3979]], grad_fn=<IndexBackward>) 
              2.. tensor([[ 0.0536],
        [-0.0122]], grad_fn=<IndexBackward>)
yay -20
complaint 8 assert approx_eq: tensor([[145],
        [153]]) 
              1.. tensor([[-857.2175],
        [-760.7724]], grad_fn=<IndexBackward>) tensor([[885.2911],
        [765.6864]], grad_fn=<IndexBackward>) tensor([[-309.9179],
        [-268.8008]], grad_fn=<IndexBackward>) tensor([[281.7830],
        [263.8986]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0613],
        [ 0.0119]], grad_fn=<IndexBackward>)
co

\
MCMC, etc. 

In [3]:
print("running...")

import sys, os

print(sys.executable)
#print(sys.path)

from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

print("making:")

multisiteMod = createScenario(tdom_fat_params)


running...
/anaconda3/bin/python
Reloading polytopize.
addHess tested
addHess tested
making:
1
testresults/scenario_N44_mu1.0_sigma2.0_nu-1.0.csv from file
44
tensor([32.5364, -3.3454,  3.2929, -2.5415])
{'hessian': tensor([[1., 0., 1.],
        [0., 2., 0.],
        [1., 0., 1.]]), 'logPosterior': 0}


In [13]:
multisiteMod.

SyntaxError: invalid syntax (<ipython-input-13-78d7c46ccca3>, line 1)

In [8]:
maxError = torch.max(errors)
print(float(maxError))

0.27889007329940796
