# Quick intro

Scratch:


In [8]:
import json
import sys
import pyro

print(pyro.__file__)


print(sys.executable)

/anaconda3/lib/python3.7/site-packages/pyro/__init__.py
/anaconda3/bin/python


Amortizable hierarchical t model:

In [1]:
from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

#vals = MIDDF35
guidenames = ["amortized_laplace","unamortized_laplace","meanfield"]#,"meanfield",]#,"MLE"]#,"laplace"
if True:

    for aniter in range(1):
        for nparticles in [1]:#,5]:
            for trueparams in [ndom_fat_params,ndom_norm_params,]:#tdom_fat_params,tdom_norm_params,]:
                for guidename in guidenames:
                    #

                    print(aniter,nparticles,guidenames,trueparams)
                    result = trainGuide(guidename,nparticles,trueparams,filename="testresults/demoT_2.csv")
                    print(aniter,nparticles,guidenames)
                    for line in range(10):
                        print()
                    
else:
    plt.plot([getMLE(.01 + x/100,1.,0,1.) for x in range(500)])
                    

Reloading polytopize.
0 1 ['amortized_laplace', 'unamortized_laplace', 'meanfield'] {'modal_effect': tensor(0.5000), 'df': tensor(-1.), 't_scale': tensor(-1.)}
1
testresults/scenario_N44_mu0.5_sigma-1.0_nu2.5+exp-1.0.csv from file
44
tensor([0.4283, 0.6877, 0.9501, 0.3907])
guidename amortized_laplace
trueparams {'modal_effect': tensor(0.5000), 'df': tensor(-1.), 't_scale': tensor(-1.)}
esize torch.Size([44])
yay 7 fix_m_grad
epoch 0 loss = 203.91335368156433;
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
yay -80
yay -140
yay -200
yay -260
epoch 100 loss = 167.21069049835205;
mode_hat tensor(0.2697, requires_grad=True)
ltscale_hat tensor(-0.4974, requires_grad=True)
ldfraw_hat tensor(0.4255, requires_grad=True)
yay -320
yay -380
yay -440
yay -500
yay -560
epoch 200 loss = 151.25056338310242;
mode_hat tensor(0.4696, requires_grad=True)
ltscale_hat tensor(

epoch 800 loss = 138.60468208789825;
mode_hat tensor(0.3228, requires_grad=True)
ltscale_hat tensor(-1.3662, requires_grad=True)
ldfraw_hat tensor(-0.8552, requires_grad=True)
epoch 900 loss = 108.64722156524658;
mode_hat tensor(0.3352, requires_grad=True)
ltscale_hat tensor(-1.3942, requires_grad=True)
ldfraw_hat tensor(-0.9321, requires_grad=True)
epoch 1000 loss = 139.76562309265137;
mode_hat tensor(0.3538, requires_grad=True)
ltscale_hat tensor(-1.3924, requires_grad=True)
ldfraw_hat tensor(-0.9714, requires_grad=True)
epoch 1100 loss = 139.522616147995;
mode_hat tensor(0.3776, requires_grad=True)
ltscale_hat tensor(-1.3495, requires_grad=True)
ldfraw_hat tensor(-1.0492, requires_grad=True)
Final mean_losses: 146.22931126398365
guidename unamortized_laplace
trueparams {'modal_effect': tensor(0.5000), 'df': tensor(-1.), 't_scale': tensor(-1.)}
full_tmode:
tensor([ 0.0396,  0.2751,  0.5534,  0.0307,  0.0809,  0.5135, -0.1532,  0.2466,
        -0.1085, -0.7611,  0.3107,  0.9810, -0.13

yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
yay -80
yay -140
yay -200
yay -260
epoch 100 loss = 157.77566063404083;
mode_hat tensor(0.2024, requires_grad=True)
ltscale_hat tensor(-0.4942, requires_grad=True)
ldfraw_hat tensor(0.4832, requires_grad=True)
yay -320
yay -380
yay -440
yay -500
yay -560
epoch 200 loss = 144.3860502243042;
mode_hat tensor(0.4801, requires_grad=True)
ltscale_hat tensor(-0.8810, requires_grad=True)
ldfraw_hat tensor(0.7424, requires_grad=True)
yay -620
yay -680
yay -740
yay -800
yay -860
epoch 300 loss = 173.44240522384644;
mode_hat tensor(0.4990, requires_grad=True)
ltscale_hat tensor(-1.0278, requires_grad=True)
ldfraw_hat tensor(0.5856, requires_grad=True)
yay -920
yay -980
yay -1040
yay -1100
yay -1160
epoch 400 loss = 143.4604811668396;
mode_hat tensor(0.4752, requires_grad=True)
ltscale_hat tensor(-1.0478, requires_grad=True)
ldfraw_hat tensor(0.4469, requires_grad=True)
yay -1220
yay -1280
yay -1340
yay -1400
yay -1460
epoch 500 loss = 173.63828372955322;


epoch 200 loss = 200.4668071269989;
mode_hat tensor(0.4123, requires_grad=True)
ltscale_hat tensor(-0.9926, requires_grad=True)
ldfraw_hat tensor(0.9174, requires_grad=True)
epoch 300 loss = 126.53612780570984;
mode_hat tensor(0.4583, requires_grad=True)
ltscale_hat tensor(-1.4876, requires_grad=True)
ldfraw_hat tensor(1.2687, requires_grad=True)
epoch 400 loss = 272.3038856983185;
mode_hat tensor(0.4686, requires_grad=True)
ltscale_hat tensor(-1.9876, requires_grad=True)
ldfraw_hat tensor(1.5156, requires_grad=True)
epoch 500 loss = 228.91440653800964;
mode_hat tensor(0.5326, requires_grad=True)
ltscale_hat tensor(-2.4876, requires_grad=True)
ldfraw_hat tensor(1.7960, requires_grad=True)
epoch 600 loss = 465.1707184314728;
mode_hat tensor(0.4800, requires_grad=True)
ltscale_hat tensor(-2.9876, requires_grad=True)
ldfraw_hat tensor(2.2094, requires_grad=True)
Final mean_losses: 316.07090844401426
guidename unamortized_laplace
trueparams {'modal_effect': tensor(0.5000), 'df': tensor(3.)

MCMC, etc.

In [3]:
print("running...")

import sys, os

print(sys.executable)
#print(sys.path)

from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

print("making:")

multisiteMod = createScenario(tdom_fat_params)


running...
/anaconda3/bin/python
Reloading polytopize.
addHess tested
addHess tested
making:
1
testresults/scenario_N44_mu1.0_sigma2.0_nu-1.0.csv from file
44
tensor([32.5364, -3.3454,  3.2929, -2.5415])
{'hessian': tensor([[1., 0., 1.],
        [0., 2., 0.],
        [1., 0., 1.]]), 'logPosterior': 0}


In [13]:
multisiteMod.

SyntaxError: invalid syntax (<ipython-input-13-78d7c46ccca3>, line 1)

In [8]:
maxError = torch.max(errors)
print(float(maxError))

0.27889007329940796
