# Quick intro

Scratch:


In [8]:
import json
import sys
import pyro

print(pyro.__file__)


print(sys.executable)

/anaconda3/lib/python3.7/site-packages/pyro/__init__.py
/anaconda3/bin/python


Amortizable hierarchical t model:

In [ ]:
from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

#vals = MIDDF35
guidenames = ["amortized_laplace","meanfield","unamortized_laplace"]#,"unamortized_laplace","meanfield",]#,"MLE"]#,"laplace"
if True:

    for aniter in range(4):
        for trueparams in [ndom_fat_params]:#,ndom_norm_params]:#,tdom_fat_params,tdom_norm_params,]:
            for nsamps,nparticles in [(10,1),(10,3),(50,1),(50,3)]:#,(100,1),(400,1)]:
                    for guidename in guidenames:
                        #

                        print(aniter,nparticles,guidenames,trueparams)
                        result = trainGuide(guidename,nparticles,trueparams,
                                            filename="testresults/demoT_2.csv",

                                            subsample_N = nsamps)
                        print(aniter,nparticles,guidenames)
                        for line in range(10):
                            print()
                    
else:
    plt.plot([getMLE(.01 + x/100,1.,0,1.) for x in range(500)])
                    

0 1 ['amortized_laplace', 'meanfield', 'unamortized_laplace'] [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu3.0.csv from file
400
tensor([-7.9208,  0.5222,  0.8593,  2.3906])
Sizes: torch.Size([400]) torch.Size([400])
guidename amortized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 10 40.0
yay 7 fix_m_grad
epoch 0 loss = 1114.9764868021011;
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(0.0050, requires_grad=True)
ldfraw_hat tensor(-0.0050, requires_grad=True)
yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
yay -80
yay -140
complaint 9 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-771.5305]], grad_fn=<IndexBackward>) tensor([[789.4745]], grad_fn=<IndexBackward>) tensor([[-276.8895]], grad_fn=<IndexBackward>) tensor([[259.0411]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.0957]], grad_fn=<IndexBackward>)
complaint 8 assert approx_eq: tensor([[15

testresults/scenario_N400_mu1.0_sigma2.0_nu3.0.csv from file
400
tensor([-7.9208,  0.5222,  0.8593,  2.3906])
Sizes: torch.Size([400]) torch.Size([400])
guidename unamortized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 10 40.0
epoch 0 loss = 2072.3795664310455;
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
epoch 100 loss = 1703.8440679311752;
mode_hat tensor(0.5050, requires_grad=True)
ltscale_hat tensor(-0.3304, requires_grad=True)
ldfraw_hat tensor(0.2016, requires_grad=True)
epoch 200 loss = 1163.0583981275558;
mode_hat tensor(1.0050, requires_grad=True)
ltscale_hat tensor(-0.5834, requires_grad=True)
ldfraw_hat tensor(0.3087, requires_grad=True)
epoch 300 loss = 1039.4693734645844;
mode_hat tensor(1.0183, requires_grad=True)
ltscale_hat tensor(-0.8257, requires_grad=True)
ldfraw_hat tensor(0.3863, requires_grad=True)
epoch 400 loss = 10

yay -740
yay -800
yay -860
epoch 300 loss = 906.9384283224742;
mode_hat tensor(0.7308, requires_grad=True)
ltscale_hat tensor(-1.0078, requires_grad=True)
ldfraw_hat tensor(0.6216, requires_grad=True)
yay -920
yay -980


\
MCMC, etc. 

In [3]:
print("running...")

import sys, os

print(sys.executable)
#print(sys.path)

from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

print("making:")

multisiteMod = createScenario(tdom_fat_params)


running...
/anaconda3/bin/python
Reloading polytopize.
addHess tested
addHess tested
making:
1
testresults/scenario_N44_mu1.0_sigma2.0_nu-1.0.csv from file
44
tensor([32.5364, -3.3454,  3.2929, -2.5415])
{'hessian': tensor([[1., 0., 1.],
        [0., 2., 0.],
        [1., 0., 1.]]), 'logPosterior': 0}


In [13]:
multisiteMod.

SyntaxError: invalid syntax (<ipython-input-13-78d7c46ccca3>, line 1)

In [8]:
maxError = torch.max(errors)
print(float(maxError))

0.27889007329940796
