# Quick intro

Scratch:


In [8]:
import json
import sys
import pyro

print(pyro.__file__)


print(sys.executable)

/anaconda3/lib/python3.7/site-packages/pyro/__init__.py
/anaconda3/bin/python


Amortizable hierarchical t model:

In [ ]:
from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

#vals = MIDDF35
guidenames = ["amortized_laplace","unamortized_laplace","meanfield"]#,"meanfield",]#,"MLE"]#,"laplace"
if True:

  for nsamps in [12,25,50,150,400]:
    for aniter in range(1):
        for nparticles in [1]:#,5]:
            for trueparams in [ndom_fat_params,ndom_norm_params,]:#tdom_fat_params,tdom_norm_params,]:
                for guidename in guidenames:
                    #

                    print(aniter,nparticles,guidenames,trueparams)
                    result = trainGuide(guidename,nparticles,trueparams,
                                        filename="testresults/demoT_2.csv",
                                      
                                        subsample_N = nsamps)
                    print(aniter,nparticles,guidenames)
                    for line in range(10):
                        print()
                    
else:
    plt.plot([getMLE(.01 + x/100,1.,0,1.) for x in range(500)])
                    

Reloading polytopize.
0 1 ['amortized_laplace', 'unamortized_laplace', 'meanfield'] {'modal_effect': tensor(0.5000), 'df': tensor(-1.), 't_scale': tensor(-1.)}
1
testresults/scenario_N400_mu0.5_sigma-1.0_nu2.5+exp-1.0.csv from file
400
tensor([-5.0434,  2.2334,  1.4021,  1.0256])
Sizes: torch.Size([400]) torch.Size([400])
guidename amortized_laplace
trueparams {'modal_effect': tensor(0.5000), 'df': tensor(-1.), 't_scale': tensor(-1.)}
esize torch.Size([400])
complaint 9 assert approx_eq: tensor([[243],
        [249]]) 
              1.. tensor([[-380.5245],
        [ 363.9728]], grad_fn=<IndexBackward>) tensor([[ 380.1057],
        [-364.1782]], grad_fn=<IndexBackward>) tensor([[-127.9025],
        [ 125.9813]], grad_fn=<IndexBackward>) tensor([[ 127.4307],
        [-125.7649]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.8907],
        [ 0.0110]], grad_fn=<IndexBackward>)
yay 7 fix_m_grad
epoch 0 loss = 850.2816998958588;
mode_hat tensor(0.0050, requires_grad=True)
ltscale

Final mean_losses: 959.2177777665873
guidename unamortized_laplace
trueparams {'modal_effect': tensor(0.5000), 'df': tensor(-1.), 't_scale': tensor(-1.)}
full_tmode:
tensor([-5.5877e+00,  1.6642e+00,  7.5992e-01,  4.0481e-01, -2.5331e-01,
        -4.6420e+00,  4.0259e-02, -1.7532e+00,  6.2105e+00, -6.1214e-02,
         1.8627e-01,  4.6547e+00,  1.2445e+00, -7.1969e-01,  3.7242e+00,
         1.0401e-01, -1.8131e-01,  1.0049e-01,  9.4860e-01,  5.4469e+00,
        -1.6185e+00, -3.7510e-01,  3.5656e+00,  1.1490e+00, -1.9292e+00,
         5.8061e+00, -2.3552e+00,  1.6891e+00, -3.9071e-01, -4.3346e-01,
        -4.9660e+00, -6.6037e+00, -4.3469e-02,  2.4780e+00,  3.0011e-01,
        -2.4950e+00,  7.7398e-01,  2.3796e+00,  2.9001e-02,  3.5642e-01,
        -3.2604e-01, -2.7054e-01,  2.3673e-01, -1.4536e+00, -5.9563e-01,
        -4.9466e-02,  5.5332e-01, -5.4207e-01,  1.3947e+00,  8.1203e+00,
         5.2905e-01,  2.0021e-01, -1.5040e+00, -2.0962e+00, -1.8171e-01,
         1.1289e-01, -1.3754e+0

yay 7 fix_m_grad
epoch 0 loss = 846.6325657367706;
mode_hat tensor(-0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
yay -80
yay -140
yay -200
yay -260
epoch 100 loss = 750.2427287101746;
mode_hat tensor(0.3088, requires_grad=True)
ltscale_hat tensor(-0.4777, requires_grad=True)
ldfraw_hat tensor(0.5011, requires_grad=True)
yay -320
yay -380
yay -440
yay -500
yay -560
epoch 200 loss = 736.6217885017395;
mode_hat tensor(0.4540, requires_grad=True)
ltscale_hat tensor(-0.8897, requires_grad=True)
ldfraw_hat tensor(0.9700, requires_grad=True)
yay -620
yay -680
yay -740
yay -800
yay -860
epoch 300 loss = 560.4170126914978;
mode_hat tensor(0.5255, requires_grad=True)
ltscale_hat tensor(-1.2243, requires_grad=True)
ldfraw_hat tensor(1.3874, requires_grad=True)
yay -920
yay -980
yay -1040
yay -1100
yay -1160
epoch 400 loss = 624.2223567962646;
mode_hat tensor(0.5633, requires_grad

MCMC, etc. 

In [3]:
print("running...")

import sys, os

print(sys.executable)
#print(sys.path)

from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

print("making:")

multisiteMod = createScenario(tdom_fat_params)


running...
/anaconda3/bin/python
Reloading polytopize.
addHess tested
addHess tested
making:
1
testresults/scenario_N44_mu1.0_sigma2.0_nu-1.0.csv from file
44
tensor([32.5364, -3.3454,  3.2929, -2.5415])
{'hessian': tensor([[1., 0., 1.],
        [0., 2., 0.],
        [1., 0., 1.]]), 'logPosterior': 0}


In [13]:
multisiteMod.

SyntaxError: invalid syntax (<ipython-input-13-78d7c46ccca3>, line 1)

In [8]:
maxError = torch.max(errors)
print(float(maxError))

0.27889007329940796
