# Quick intro

This is a jupyter notebook for testing / coding. So far, each code block is a separate test; unlike an ordinary notebook, they are not meant to run sequentially.

Let's do MCMC:


Next, running "ei". This started out as a copy of Fritz's code but it's evolved into a working version of ours.

In [ ]:
from importlib import reload
import ei_multisampleQ #import *
reload(ei_multisampleQ)
from ei_multisampleQ import *
import cProfile as profile

#ec,erc = legible_values(3,3)
#print(ec,"\n",erc,"\n",ec+erc)
#inits = good_inits(1.)
#del inits["ercstar_raw"]
for (nsamps,subn) in [(15,100)]:#[(2,60),(5,60),(2,30),(20,30),(40,5)]:
    
    for i in range(10):
        for sigma_nu in [ .3,.1,  .02,]: #.02, 
            #%prun result = trainGuide(nsamps=nsamps,subsample_n=subn)#inits = inits)
            trainGuide(nsamps=nsamps,subsample_n=subn,sigmanu=sigma_nu,dversion=i, force_full=True)#,inits = inits)
            #modelQvar(sigmanu=sigma_nu)#,samps=5)
            

base:Yes, I will run. line 5 2 :
Reloading polytopize.
base:Yes, I will run. line 5 3 :
Reloading polytopize.
exception: [Errno 2] No such file or directory: 'ei_post_results_fixedalpha/scenario_SIG0.3_0_N2774.csv'
alpha beta line 51 1 :
     tensor([ 0.2800,  0.2000, -0.4800])
     tensor([[-0.1500, -0.4300,  0.9400],
        [ 0.0100,  0.4900, -1.2300],
        [ 0.1400, -0.0600,  0.3000]])
ec:tensor([ 0.2800,  0.2000, -0.4800]) line 51 1 :
erc:tensor([[-0.1500, -0.4300,  0.9400],
        [ 0.0100,  0.4900, -1.2300],
        [ 0.1400, -0.0600,  0.3000]]) line 51 1 :
y[0]:tensor([[1136.,  449., 1295.],
        [  90.,  126.,    8.],
        [  43.,   34.,   27.]]) line 51 1 :
VS tensor([[1269.,  609., 1330.],
        [1023.,  946., 1248.],
        [1341., 1292., 1693.],
        [ 663.,  360., 1299.]])
ei_post_results_fixedalpha/scenario_SIG0.3_0_N2774.csv created
svi.step(... line 51 1 :
     0
     27.74
     torch.Size([100, 9])
guide:begin line 51 1 :
     27.74
     True
types? li

sds: tensor(0.3465, grad_fn=<StdBackward0>) tensor(0.3317, requires_grad=True) tensor(0.3007, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0477, -0.1015], grad_fn=<SliceBackward>)
epoch 90 loss = 6.07E+08, mean_loss=7.04E+08;
 logitstar = tensor([[ 0.0696, -0.1443,  0.0747],
        [ 0.0281, -0.0646,  0.0366],
        [ 0.0456, -0.0957,  0.0501]], grad_fn=<AddBackward0>)
sds: tensor(0.2838, grad_fn=<StdBackward0>) tensor(0.2728, requires_grad=True) tensor(0.2452, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0449, -0.0938], grad_fn=<SliceBackward>)
epoch 100 loss = 6.86E+08, mean_loss=7.02E+08;
 logitstar = tensor([[ 0.0707, -0.1494,  0.0787],
        [ 0.0172, -0.0499,  0.0328],
        [ 0.0466, -0.0820,  0.0353]], grad_fn=<AddBackward0>)
sds: tensor(0.2905, grad_fn=<StdBackward0>) tensor(0.2789, requires_grad=True) tensor(0.2490, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([ 0.0414, -0.0975], grad_fn=<SliceBackward>)
epoch 110 loss = 7.35E+08, mean_loss=7.05E+08;
 logitstar

    Size 6: [400]; noNAN
sampleYs line 1419 6 :
     
    Size 0: [400, 13]; noNAN
    Size 1: [400, 1, 13]; noNAN
    Size 2: [13]; noNAN
    Size 3: [694, 13, 13]; noNAN
    Size 4: [400, 7]; noNAN
    Size 5: [400, 3, 3]; noNAN
    Size 6: [400, 1]; noNAN
np complete? line 1311 7 :
     
    Size 0: [400]; noNAN
    Size 1: [400, 3, 3]; noNAN
    Size 2: [400, 9]; noNAN
    Size 3: [400, 3, 3]; noNAN
    Size 4: [400]; noNAN
    Size 5: [400, 9]; noNAN
    Size 6: [400]; noNAN
sampleYs line 1419 7 :
     
    Size 0: [400, 13]; noNAN
    Size 1: [400, 1, 13]; noNAN
    Size 2: [13]; noNAN
    Size 3: [694, 13, 13]; noNAN
    Size 4: [400, 7]; noNAN
    Size 5: [400, 3, 3]; noNAN
    Size 6: [400, 1]; noNAN
np complete? line 1311 8 :
     
    Size 0: [400]; noNAN
    Size 1: [400, 3, 3]; noNAN
    Size 2: [400, 9]; noNAN
    Size 3: [400, 3, 3]; noNAN
    Size 4: [400]; noNAN
    Size 5: [400, 9]; noNAN
    Size 6: [400]; noNAN
sampleYs line 1419 8 :
     
    Size 0: [400, 13]; noN

types? line 100 32
sds: tensor(0.2669, grad_fn=<StdBackward0>) tensor(0.2503, requires_grad=True) tensor(0.2141, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.0508, -0.0550], grad_fn=<SliceBackward>)
epoch 10 loss = 6.97E+08, mean_loss=7.60E+08;
 logitstar = tensor([[-0.0445, -0.0529,  0.0974],
        [-0.0501, -0.0570,  0.1070],
        [-0.0578, -0.0551,  0.1129]], grad_fn=<AddBackward0>)
svi.step(... line 51 16
guide:begin line 51 16
lp:  line 51 16
guide:end line 51 16
model:end line 51 32
sds: tensor(0.2652, grad_fn=<StdBackward0>) tensor(0.2531, requires_grad=True) tensor(0.2210, grad_fn=<StdBackward0>)
ps2
 ecstar = tensor([-0.0611, -0.0917], grad_fn=<SliceBackward>)
epoch 20 loss = 6.91E+08, mean_loss=7.54E+08;
 logitstar = tensor([[-0.0549, -0.0982,  0.1531],
        [-0.0670, -0.0912,  0.1582],
        [-0.0615, -0.0859,  0.1473]], grad_fn=<AddBackward0>)
types? line 100 64
sds: tensor(0.3400, grad_fn=<StdBackward0>) tensor(0.3347, requires_grad=True) tensor(0.2963, grad_


.

.

.



In [2]:
from importlib import reload
import ei_multisample #import *
reload(ei_multisample)
from ei_multisample import *
import cProfile as profile

inits = dict() #good_inits()
#del inits["ercstar_raw"]
#%prun result = trainGuide(inits = inits)

NCparams = EIData.load("NC_Data/NC_2016_statewide_alpha_and_beta.csv")
print(NCparams.alpha + NCparams.beta)
#print("components")
#print(NCparams.alpha)
#
#print(NCparams.beta)
print(SIM_SIGMA_NU)
SIM_SIGMA_NU = 0.001
print(ei_multisample.SIM_SIGMA_NU)
ei_multisample.SIM_SIGMA_NU = .0001
print(ei_multisample.SIM_SIGMA_NU)

base:Yes, I will run. line 5 3 :
Reloading polytopize.
tensor([[ 0.0500, -0.9100,  1.2200],
        [ 0.2100,  0.0100, -0.9500],
        [ 0.3400, -0.5400,  0.5800]])
0.15
0.15
0.0001


# Testing hessian transparency

In [18]:
import torch
ts = torch.tensor
os = torch.ones
zs = torch.zeros
from importlib import reload
import myhessian
reload(myhessian)

t1 = os(2,2,requires_grad=True)
r = torch.sum(t1 * t1 * t1)

h = myhessian.hessian(r,t1)
print("hess",h)
r2 = torch.sum(h * h)
[r3] = torch.autograd.grad(r,t1,create_graph=True,retain_graph=True)
print("d ",r3)
print("Σd ",torch.sum(r3))
[r4] = torch.autograd.grad(torch.sum(r3),t1,create_graph=True,retain_graph=True)
print("dΣdΣd ",torch.autograd.grad(torch.sum(r4),t1,create_graph=True,retain_graph=True))
print(torch.autograd.grad(r2,t1))

hess tensor([[6., 0., 0., 0.],
        [0., 6., 0., 0.],
        [0., 0., 6., 0.],
        [0., 0., 0., 6.]], grad_fn=<CopySlices>)
d  tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
Σd  tensor(12., grad_fn=<SumBackward0>)
dΣdΣd  (tensor([[6., 6.],
        [6., 6.]]),)
(tensor([[72., 72.],
        [72., 72.]]),)


In [4]:
import sys
import hessian

from importlib import reload
import polytopize #import *
reload(polytopize)
from polytopize import *

import tests


Yes, I will run.
Yes, I will run.
ge fail
loc tensor([[ 0.3147],
        [ 2.4440],
        [-4.0535],
        [ 2.2007]])
polytopedLoc tensor([[ 2.1063e-01,  2.1136e-02],
        [ 2.8514e-01, -1.8626e-09],
        [ 3.4959e-01,  9.9957e-02],
        [ 3.5462e-01,  1.1892e-02],
        [ 2.5462e+00,  3.2228e-01]])
ge fail
loc tensor([[-5.8855],
        [-5.2805],
        [ 5.4654],
        [ 0.1889]])
polytopedLoc tensor([[ 2.8885e-01,  1.1871e+00],
        [ 8.5629e-01,  2.0505e+00],
        [ 3.9984e-01, -1.4901e-08],
        [ 9.5542e-01,  1.5538e+00],
        [ 1.0063e+00,  9.9522e-01]])
Reloading cmult...
callable? <bound method TorchDistributionMixin.__call__ of Multinomial()>
callable? <bound method TorchDistributionMixin.__call__ of TorchCMult()>
Sampling multinomial: tensor([1., 2.])
Sampling cm2: tensor([0., 3.])
tensor(5.6022, grad_fn=<NegBackward>) tensor([[112.2500]])


# Test rank1torch (to get yhat from pi,n,v)

In [10]:
from importlib import reload
import rank1torch #import *
reload(rank1torch)
from rank1torch import *

test_solver()

Testing optimize_Q (50 tests): 
R=3, C=5, tolerance=0.001
Oh no! In test 3, Q has some negative entries:
	 trueQ[2][4]=0.00010659269901225343, 
	     Q[2][4]=-0.00021605131041724235
Oh no! In test 5, Q has some negative entries:
	 trueQ[1][4]=0.00011974151857430115, 
	     Q[1][4]=-1.1631345842033625e-06
Oh no! In test 8, Q has some negative entries:
	 trueQ[0][1]=2.882161788875237e-05, 
	     Q[0][1]=-0.0004783869662787765
Oh no! In test 15, Q has some negative entries:
	 trueQ[2][3]=0.0007846675580367446, 
	     Q[2][3]=-6.166117964312434e-05
Oh no! In test 28, Q has some negative entries:
	 trueQ[0][4]=8.13114020274952e-05, 
	     Q[0][4]=-0.00018321917741559446
Oh no! In test 40, Q has some negative entries:
	 trueQ[2][3]=0.00032634526723995805, 
	     Q[2][3]=-0.000617634505033493
Oh no! In test 47, Q has some negative entries:
	 trueQ[2][1]=0.00017936740186996758, 
	     Q[2][1]=-0.00041433278238400817
Oh no! In test 48, Q has some negative entries:
	 trueQ[0][0]=4.52485837740823

## Overview

Most SVI problems in pyro are coded as a model, a generic guide (such as: multivariate Gaussian in all parameters), and specific observations/data (passed as arguments to svi.step). For EI, that's going to be different; the observations are going to be built into the guide function, leaving nothing to include in the "data" argument to svi.step.

That means there is a lot of work for the guide to do. As usual, it must establish reasonable distributional families for the posterior of each of the hyperparameters. But for the latent parameters, the job of the guide is to take a "relative strength" number for each race/candidate/precinct combo, and turn that into a number of votes for each combo, such that those numbers obey all the constraints set by observations. This means that for each precinct (considered separately), the latent guide must:

-Find the "center point" where candidate preference is independent of race.

-Find the "basis vectors" (actually, there are more than enough of them to form a basis) which determine the directions to move in the space.

-For any given set of "relative strengths" which is a distance $d$ in a direction $\theta$, find the first constraint violated when moving in that direction, and the distance $r$ between the origin and that constraint.

-Project the "relative strengths" onto the numbers of votes, by moving $r(1-e^{-d})$ in direction $\theta$.

#### a = zs(2,2,2,2)
a[0,1,1,1] = 2
print(a[1,1])
print(a[0,1])
print(torch.max(a))
print(torch.distributions.exponential.Exponential(ts([1])).sample(4))