# Quick intro

This is a jupyter notebook for testing / coding. So far, each code block is a separate test; unlike an ordinary notebook, they are not meant to run sequentially.

First, test to see jupyter is running correctly at all:


In [33]:
import os
import sys

print("hi!!!")

hi!!!
hi!!!
hi!!!
hi!!!
hi!!!


Next, running "toypyro". This started out as a copy of Fritz's code but I hope it evolves into a working version of ours.

In [1]:
from importlib import reload
import ei #import *
reload(ei)
from ei import *
import cProfile as profile

%prun result = trainGuide()

Yes, I will run.
Reloading cmult...
Yes, I will run.
Yes, I will run.
ec:tensor([-0.0581, -0.2141,  0.2529])
erc:tensor([[0., 1., 2.],
        [2., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
y[0]:tensor([[ 24.,  84., 325.],
        [252.,  25.,  45.],
        [ 74.,  46.,  87.],
        [ 22.,  23.,  43.]])
(tensor([[ 433.,  322.,  207.,   88.],
        [ 432.,  342.,  244.,  154.],
        [ 435.,  362.,  285.,  212.],
        [ 434.,  382.,  330.,  278.],
        [ 429.,  402.,  371.,  336.],
        [ 428.,  422.,  408.,  402.],
        [ 431.,  442.,  449.,  460.],
        [ 430.,  462.,  494.,  526.],
        [ 425.,  482.,  535.,  584.],
        [ 424.,  502.,  572.,  650.],
        [ 427.,  522.,  613.,  708.],
        [ 426.,  542.,  658.,  774.],
        [ 421.,  562.,  699.,  832.],
        [ 420.,  582.,  736.,  898.],
        [ 423.,  602.,  777.,  956.],
        [ 422.,  622.,  822., 1022.],
        [ 417.,  642.,  863., 1080.],
        [ 416.,  662.,  900., 114

epoch 410 loss = 832.488821387291; logsdrchat = -0.04627925157546997; erchat[0] = tensor([-0.0264, -0.0691,  0.0932], grad_fn=<SelectBackward>)
epoch 420 loss = 839.9306443929672; logsdrchat = -0.09615467488765717; erchat[0] = tensor([-0.0272, -0.0856,  0.1018], grad_fn=<SelectBackward>)
epoch 430 loss = 827.0378839969635; logsdrchat = -0.1462113857269287; erchat[0] = tensor([-0.0283, -0.0832,  0.1032], grad_fn=<SelectBackward>)
epoch 440 loss = 839.1318674087524; logsdrchat = -0.19632850587368011; erchat[0] = tensor([-0.0332, -0.0901,  0.1115], grad_fn=<SelectBackward>)
epoch 450 loss = 822.6805595159531; logsdrchat = -0.24646398425102234; erchat[0] = tensor([-0.0280, -0.0945,  0.1209], grad_fn=<SelectBackward>)
epoch 460 loss = 808.0235008001328; logsdrchat = -0.29660332202911377; erchat[0] = tensor([-0.0191, -0.0800,  0.1172], grad_fn=<SelectBackward>)
epoch 470 loss = 842.6411890983582; logsdrchat = -0.34674155712127686; erchat[0] = tensor([-0.0188, -0.0814,  0.1271], grad_fn=<Sele

epoch 980 loss = 794.684400677681; logsdrchat = -2.9008307456970215; erchat[0] = tensor([-0.0489, -0.0634,  0.1322], grad_fn=<SelectBackward>)
epoch 990 loss = 795.3051247596741; logsdrchat = -2.9505867958068848; erchat[0] = tensor([-0.0498, -0.0606,  0.1297], grad_fn=<SelectBackward>)
epoch 1000 loss = 807.6737458705902; logsdrchat = -3.000250816345215; erchat[0] = tensor([-0.0457, -0.0548,  0.1282], grad_fn=<SelectBackward>)
epoch 1010 loss = 785.0010625123978; logsdrchat = -3.049680233001709; erchat[0] = tensor([-0.0484, -0.0583,  0.1340], grad_fn=<SelectBackward>)
epoch 1020 loss = 799.0881142616272; logsdrchat = -3.099195957183838; erchat[0] = tensor([-0.0415, -0.0700,  0.1421], grad_fn=<SelectBackward>)
epoch 1030 loss = 801.2452833652496; logsdrchat = -3.1468701362609863; erchat[0] = tensor([-0.0465, -0.0521,  0.1336], grad_fn=<SelectBackward>)
tensor([[ 0.2440, -0.0035,  0.0448,  0.0261, -0.0437, -0.0248],
        [-0.0035,  0.2519,  0.0243,  0.0153, -0.0239, -0.0126],
        

ValueError: The parameter covariance_matrix has invalid values
Trace Shapes:          
 Param Sites:          
  precinctpsi    6     
   logsdrchat          
        echat    3     
       erchat 4  3     
       what_0 3  2     
       what_1 3  2     
       what_2 3  2     
       what_3 3  2     
       what_4 3  2     
       what_5 3  2     
       what_6 3  2     
       what_7 3  2     
       what_8 3  2     
       what_9 3  2     
      what_10 3  2     
      what_11 3  2     
      what_12 3  2     
      what_13 3  2     
      what_14 3  2     
      what_15 3  2     
      what_16 3  2     
      what_17 3  2     
      what_18 3  2     
      what_19 3  2     
      what_20 3  2     
      what_21 3  2     
      what_22 3  2     
      what_23 3  2     
      what_24 3  2     
      what_25 3  2     
      what_26 3  2     
      what_27 3  2     
      what_28 3  2     
      what_29 3  2     
    globalpsi   16     
Sample Sites:          
   theta dist    | 16  
        value    | 16  
    sdrc dist    |     
        value    |     
      ec dist    |  3  
        value    |  3  
     erc dist    |  4 3
        value    |  4 3
     w_0 dist    |  6  
        value    |  6  
   y_0_0 dist    |  3  
        value    |  3  
   y_0_1 dist    |  3  
        value    |  3  
   y_0_2 dist    |  3  
        value    |  3  
   y_0_3 dist    |  3  
        value    |  3  
     w_1 dist    |  6  
        value    |  6  
   y_1_0 dist    |  3  
        value    |  3  
   y_1_1 dist    |  3  
        value    |  3  
   y_1_2 dist    |  3  
        value    |  3  
   y_1_3 dist    |  3  
        value    |  3  
     w_2 dist    |  6  
        value    |  6  
   y_2_0 dist    |  3  
        value    |  3  
   y_2_1 dist    |  3  
        value    |  3  
   y_2_2 dist    |  3  
        value    |  3  
   y_2_3 dist    |  3  
        value    |  3  
     w_3 dist    |  6  
        value    |  6  
   y_3_0 dist    |  3  
        value    |  3  
   y_3_1 dist    |  3  
        value    |  3  
   y_3_2 dist    |  3  
        value    |  3  
   y_3_3 dist    |  3  
        value    |  3  

Next, run "polytopize", which has all of my pre-Fritz attempts to code.

In [8]:

pyroStore = pyro.get_param_store()
for (key, val) in sorted(pyroStore.items()):
    print(f"{key}:\n{val}")

echat:
tensor([ 0.2325, -0.3407,  0.3230], requires_grad=True)
erchat:
tensor([[-0.0440, -0.0448,  0.1284],
        [-0.0490, -0.0334,  0.1120],
        [-0.0486, -0.0243,  0.0850],
        [-0.0567, -0.0134,  0.0715]], requires_grad=True)
globalpsi:
tensor([0.0116, 0.0103, 0.0103, 0.0103, 0.0103, 0.0097, 0.0097, 0.0103, 0.0097,
        0.0103, 0.0097, 0.0103, 0.0097, 0.0103, 0.0103, 0.0097],
       grad_fn=<AddBackward0>)
logsdrchat:
-3.1609883308410645
precinctpsi:
tensor([0.0010, 0.0023, 0.0028, 0.0030, 0.0031, 0.0037],
       grad_fn=<AddBackward0>)
what_0:
tensor([[-0.3764, -0.7578],
        [-0.0823,  0.0420],
        [ 0.0860,  0.2053]], requires_grad=True)
what_1:
tensor([[-0.4335, -0.9360],
        [-0.1274, -0.0898],
        [ 0.0445,  0.1291]], requires_grad=True)
what_10:
tensor([[-0.5429, -1.4944],
        [-0.2548, -0.4453],
        [-0.1268, -0.1337]], requires_grad=True)
what_11:
tensor([[-0.5426, -1.5142],
        [-0.2566, -0.4580],
        [-0.1367, -0.1516]], requir

In [6]:
yhat1 = polytopize(4,3,pyro.get_param_store()["what_0"],
                 get_indep(4,3,ts([68.,20,25,56]),ts([63.,32,74])))

erchat = pyro.get_param_store()["erchat"]

print(pyro.get_param_store()["what_0"])
print(erchat)
print(recenter_rc(erchat))
print(pyro.get_param_store()["logsdrchat"])

tensor([[-0.3764, -0.7578],
        [-0.0823,  0.0420],
        [ 0.0860,  0.2053]], requires_grad=True)
tensor([[-0.0440, -0.0448,  0.1284],
        [-0.0490, -0.0334,  0.1120],
        [-0.0486, -0.0243,  0.0850],
        [-0.0567, -0.0134,  0.0715]], requires_grad=True)
tensor([[ 0.0031, -0.0173,  0.0341],
        [-0.0019, -0.0059,  0.0177],
        [-0.0015,  0.0032, -0.0093],
        [-0.0096,  0.0141, -0.0227]], grad_fn=<SubBackward0>)
tensor(-3.1610, requires_grad=True)


In [ ]:
import pstats
p = pstats.Stats(runstats)
p.strip_dirs().sort_stats(-1).print_stats()

In [4]:
import sys
import hessian

from importlib import reload
import polytopize #import *
reload(polytopize)
from polytopize import *

import tests


Yes, I will run.
Yes, I will run.
ge fail
loc tensor([[ 0.3147],
        [ 2.4440],
        [-4.0535],
        [ 2.2007]])
polytopedLoc tensor([[ 2.1063e-01,  2.1136e-02],
        [ 2.8514e-01, -1.8626e-09],
        [ 3.4959e-01,  9.9957e-02],
        [ 3.5462e-01,  1.1892e-02],
        [ 2.5462e+00,  3.2228e-01]])
ge fail
loc tensor([[-5.8855],
        [-5.2805],
        [ 5.4654],
        [ 0.1889]])
polytopedLoc tensor([[ 2.8885e-01,  1.1871e+00],
        [ 8.5629e-01,  2.0505e+00],
        [ 3.9984e-01, -1.4901e-08],
        [ 9.5542e-01,  1.5538e+00],
        [ 1.0063e+00,  9.9522e-01]])
Reloading cmult...
callable? <bound method TorchDistributionMixin.__call__ of Multinomial()>
callable? <bound method TorchDistributionMixin.__call__ of TorchCMult()>
Sampling multinomial: tensor([1., 2.])
Sampling cm2: tensor([0., 3.])
tensor(5.6022, grad_fn=<NegBackward>) tensor([[112.2500]])


In [ ]:
loc2

result = polytopize(R,C,loc2,indep)

loc3 = depolytopize(R,C,result,indep)

print(loc2)
print(result-indep)
print(loc3)

Finally, this is a cell for directly experimenting with pytorch and/or pyro. Basically, for getting the tensor syntax right. 

In [ ]:
import torch
import cmult
import pyro
from importlib import reload
reload(cmult)
from cmult import CMult

#print(CMult(probs=torch.tensor([1., 1., 1., 1.])).log_prob(torch.tensor([1.2, 1.5, 1., 1.])))

#print(CMult(100, torch.tensor([ 1., 1., 1., 1.])).sample())

R, C = (3,4)

y = pyro.distributions.Normal(0.,4.).sample(torch.Size([R-1,C-1]))


w = torch.cat((y,-y.sum(1).unsqueeze(1)),1)
w = torch.cat((w,-w.sum(0).unsqueeze(0)),0)

#print(w)
b = w.argmax()
print(b)
print(w,w[b//C,b % C])

tt = torch.zeros(R,C)
print(tt,R,C,tt[:(R-1),:(C-1)])

## Overview

Most SVI problems in pyro are coded as a model, a generic guide (such as: multivariate Gaussian in all parameters), and specific observations/data (passed as arguments to svi.step). For EI, that's going to be different; the observations are going to be built into the guide function, leaving nothing to include in the "data" argument to svi.step.

That means there is a lot of work for the guide to do. As usual, it must establish reasonable distributional families for the posterior of each of the hyperparameters. But for the latent parameters, the job of the guide is to take a "relative strength" number for each race/candidate/precinct combo, and turn that into a number of votes for each combo, such that those numbers obey all the constraints set by observations. This means that for each precinct (considered separately), the latent guide must:

-Find the "center point" where candidate preference is independent of race.

-Find the "basis vectors" (actually, there are more than enough of them to form a basis) which determine the directions to move in the space.

-For any given set of "relative strengths" which is a distance $d$ in a direction $\theta$, find the first constraint violated when moving in that direction, and the distance $r$ between the origin and that constraint.

-Project the "relative strengths" onto the numbers of votes, by moving $r(1-e^{-d})$ in direction $\theta$.

#### a = zs(2,2,2,2)
a[0,1,1,1] = 2
print(a[1,1])
print(a[0,1])
print(torch.max(a))
print(torch.distributions.exponential.Exponential(ts([1])).sample(4))

In [ ]:
print("hi","world")
a = zs(2,2,2,2)
a[0,1,1,1] = 2 
print(torch.max(a[0,1])) 
print(pyro.distributions.Exponential(1.).sample(torch.Size([3])))
a.add_(torch.ones(2,2,2))
print(torch.exp)