# Quick intro

Scratch:


In [8]:
import json
import sys
import pyro

print(pyro.__file__)


print(sys.executable)

/anaconda3/lib/python3.7/site-packages/pyro/__init__.py
/anaconda3/bin/python


Amortizable hierarchical t model:

In [ ]:
from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

#vals = MIDDF35
guidenames = ["unparametrized_laplace","fully_amortized",]#"meanfield","amortized_laplace",]#,"unamortized_laplace","meanfield",]#,"MLE"]#,"laplace"
if True:

    for aniter in range(5):
        for trueparams in [ndom_fat_params]:#,ndom_norm_params]:#,tdom_fat_params,tdom_norm_params,]:
            for nsamps,nparticles in [(10,1),(50,1),(100,1),(399,1),(100,3),]:#(10,1),(10,3),(50,1),(50,3),(100,1),(400,1)]:#(44,5)]:#]:#,
                    for guidename in guidenames:
                        #

                        print(aniter,nparticles,guidenames,trueparams)
                        result = trainGuide(guidename,nparticles,trueparams,
                                            filename="testresults/demoT_2.csv",

                                            subsample_N = nsamps,
                                           name_offset=10)
                        print(aniter,nparticles,guidenames)
                        for line in range(10):
                            print()
                    
else:
    plt.plot([getMLE(.01 + x/100,1.,0,1.) for x in range(500)])
                    

0 1 ['unparametrized_laplace', 'fully_amortized'] [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu3.0.csv from file
400
tensor([-7.9208,  0.5222,  0.8593,  2.3906])
Sizes: torch.Size([400]) torch.Size([400])
guidename unparametrized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 10 40.0
yay 7 fix_m_grad
epoch 0 loss = 1114.9764868021011; mean_loss= 1114.9764868021011; ()
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(0.0050, requires_grad=True)
ldfraw_hat tensor(-0.0050, requires_grad=True)
yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
yay -80
yay -140
complaint 9 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-758.1817]], grad_fn=<IndexBackward>) tensor([[775.8912]], grad_fn=<IndexBackward>) tensor([[-273.3251]], grad_fn=<IndexBackward>) tensor([[255.5488]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0668]], grad_fn=<IndexBackward>)
complaint 8 a

        [ 0.0213]], grad_fn=<IndexBackward>)
complaint 5 assert approx_eq: tensor([[ 32],
        [145]]) 
              1.. tensor([[-930.1831],
        [-921.7521]], grad_fn=<IndexBackward>) tensor([[954.0871],
        [925.3885]], grad_fn=<IndexBackward>) tensor([[-316.3589],
        [-288.9171]], grad_fn=<IndexBackward>) tensor([[292.3716],
        [285.3037]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0833],
        [ 0.0231]], grad_fn=<IndexBackward>)
complaint 4 assert approx_eq: tensor([[ 32],
        [145]]) 
              1.. tensor([[-931.1666],
        [-923.1570]], grad_fn=<IndexBackward>) tensor([[955.2330],
        [926.7994]], grad_fn=<IndexBackward>) tensor([[-315.9493],
        [-288.5144]], grad_fn=<IndexBackward>) tensor([[291.9459],
        [284.8919]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.0630],
        [0.0198]], grad_fn=<IndexBackward>)
yay -20
yay -80
yay -140
yay -200
complaint 3 assert approx_eq: tensor([[153]]) 
              

        [145]]) 
              1.. tensor([[-990.1341],
        [ 935.6375],
        [-887.3495]], grad_fn=<IndexBackward>) tensor([[ 996.6469],
        [-970.0935],
        [ 904.0704]], grad_fn=<IndexBackward>) tensor([[-299.2257],
        [ 329.7215],
        [-302.0611]], grad_fn=<IndexBackward>) tensor([[ 292.7020],
        [-295.8618],
        [ 285.6404]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0108],
        [-0.5963],
        [ 0.3001]], grad_fn=<IndexBackward>)
complaint 0 assert approx_eq: tensor([[ 40],
        [145]]) 
              1.. tensor([[ 935.6901],
        [-889.2817]], grad_fn=<IndexBackward>) tensor([[-969.6515],
        [ 905.8447]], grad_fn=<IndexBackward>) tensor([[ 329.2761],
        [-301.8151]], grad_fn=<IndexBackward>) tensor([[-295.2036],
        [ 285.2911]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.1111],
        [0.0391]], grad_fn=<IndexBackward>)
complaint 0
yay -20
yay -80
yay -140
yay -200
complaint -20
yay -260
epoch

mode_hat tensor(1.0988, requires_grad=True)
ltscale_hat tensor(-1.3113, requires_grad=True)
ldfraw_hat tensor(0.0175, requires_grad=True)
complaint -160
yay -920
complaint -180
yay -980
yay -1040
yay -1100
yay -1160
epoch 400 loss = 1095.3367644548416; mean_loss= 1081.2989643651654; ()
mode_hat tensor(1.1144, requires_grad=True)
ltscale_hat tensor(-1.6775, requires_grad=True)
ldfraw_hat tensor(-0.1493, requires_grad=True)
yay -1220
yay -1280
yay -1340
yay -1400
yay -1460
epoch 500 loss = 1175.3569810390472; mean_loss= 1078.736491454871; ()
mode_hat tensor(1.1217, requires_grad=True)
ltscale_hat tensor(-2.0399, requires_grad=True)
ldfraw_hat tensor(-0.3504, requires_grad=True)
complaint -200
yay -1520
complaint -220
yay -1580
complaint -240
yay -1640
yay -1700
yay -1760
epoch 600 loss = 1050.5284695625305; mean_loss= 1076.453908027597; ()
mode_hat tensor(1.1400, requires_grad=True)
ltscale_hat tensor(-2.4252, requires_grad=True)
ldfraw_hat tensor(-0.5185, requires_grad=True)
yay -1820
c

epoch 200 loss = 1038.8694776892662; mean_loss= 1100.0994978172098; ()
mode_hat tensor(0.9311, requires_grad=True)
ltscale_hat tensor(-0.9564, requires_grad=True)
ldfraw_hat tensor(0.1616, requires_grad=True)
yay -620
complaint -100
yay -680
yay -740
complaint -120
yay -800
yay -860
epoch 300 loss = 1068.1525381207466; mean_loss= 1092.1148171107927; ()
mode_hat tensor(1.1126, requires_grad=True)
ltscale_hat tensor(-1.3858, requires_grad=True)
ldfraw_hat tensor(-0.0627, requires_grad=True)
yay -920
yay -980
complaint -140
yay -1040
yay -1100
yay -1160
complaint -160
epoch 400 loss = 1143.6267414093018; mean_loss= 1090.0518272547934; ()
mode_hat tensor(1.1522, requires_grad=True)
ltscale_hat tensor(-1.8056, requires_grad=True)
ldfraw_hat tensor(-0.2937, requires_grad=True)
yay -1220
complaint -180
yay -1280
yay -1340
complaint -200
yay -1400
complaint -220
yay -1460
epoch 500 loss = 1113.942144036293; mean_loss= 1088.1050357629263; ()
mode_hat tensor(1.1187, requires_grad=True)
ltscale_h

ldfraw_hat tensor(-0.3428, requires_grad=True)
complaint -200
yay -1220
complaint -220
yay -1280
yay -1340
yay -1400
yay -1460
epoch 500 loss = 1068.9547646045685; mean_loss= 1090.9346453509359; ()
mode_hat tensor(1.1234, requires_grad=True)
ltscale_hat tensor(-2.2800, requires_grad=True)
ldfraw_hat tensor(-0.5670, requires_grad=True)
yay -1520
yay -1580
yay -1640
complaint -240
yay -1700
complaint -260
yay -1760
epoch 600 loss = 1105.5391873121262; mean_loss= 1090.0435182596862; ()
mode_hat tensor(1.1221, requires_grad=True)
ltscale_hat tensor(-2.7161, requires_grad=True)
ldfraw_hat tensor(-0.7432, requires_grad=True)
complaint -280
yay -1820
complaint -300
yay -1880
yay -1940
complaint -320
yay -2000
complaint -340
yay -2060
epoch 700 loss = 1067.8420711755753; mean_loss= 1087.9753042979764; ()
mode_hat tensor(1.1288, requires_grad=True)
ltscale_hat tensor(-3.1647, requires_grad=True)
ldfraw_hat tensor(-0.9281, requires_grad=True)
yay -2120
yay -2180
yay -2240
yay -2300
yay -2360
epo

        [-771.1169]], grad_fn=<IndexBackward>) tensor([[906.8123],
        [771.3503]], grad_fn=<IndexBackward>) tensor([[-298.9989],
        [-265.1441]], grad_fn=<IndexBackward>) tensor([[282.9576],
        [264.9712]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.0641],
        [0.0605]], grad_fn=<IndexBackward>)
yay -20
complaint 2 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-775.4036]], grad_fn=<IndexBackward>) tensor([[775.4724]], grad_fn=<IndexBackward>) tensor([[-264.0587]], grad_fn=<IndexBackward>) tensor([[263.8278]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.1622]], grad_fn=<IndexBackward>)
complaint 1 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-777.2195]], grad_fn=<IndexBackward>) tensor([[777.5278]], grad_fn=<IndexBackward>) tensor([[-263.2519]], grad_fn=<IndexBackward>) tensor([[263.1011]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.1576]], grad_fn=<IndexBackward>)
complaint 0 assert approx_eq: tenso

              1.. tensor([[-777.5010]], grad_fn=<IndexBackward>) tensor([[781.0977]], grad_fn=<IndexBackward>) tensor([[-264.0170]], grad_fn=<IndexBackward>) tensor([[261.0092]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.5889]], grad_fn=<IndexBackward>)
complaint 1 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-782.1295]], grad_fn=<IndexBackward>) tensor([[784.6190]], grad_fn=<IndexBackward>) tensor([[-264.0988]], grad_fn=<IndexBackward>) tensor([[260.7031]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.9061]], grad_fn=<IndexBackward>)
complaint 0 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-782.3223]], grad_fn=<IndexBackward>) tensor([[785.1725]], grad_fn=<IndexBackward>) tensor([[-263.6932]], grad_fn=<IndexBackward>) tensor([[260.4102]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.4328]], grad_fn=<IndexBackward>)
complaint 0
yay -80
yay -140
yay -200
yay -260
epoch 100 loss = 1020.7107657194138; mean_loss= 1032.926

        [-877.5406]], grad_fn=<IndexBackward>) tensor([[  928.3318],
        [-1034.9326],
        [  893.7292]], grad_fn=<IndexBackward>) tensor([[-327.0853],
        [ 309.6724],
        [-302.0246]], grad_fn=<IndexBackward>) tensor([[ 294.1312],
        [-299.6739],
        [ 287.0066]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0682],
        [-0.0122],
        [ 1.1706]], grad_fn=<IndexBackward>)
complaint 8 assert approx_eq: tensor([[ 32],
        [ 40],
        [145]]) 
              1.. tensor([[-895.4459],
        [1024.9220],
        [-878.7259]], grad_fn=<IndexBackward>) tensor([[  928.3318],
        [-1034.9326],
        [  894.5338]], grad_fn=<IndexBackward>) tensor([[-327.0853],
        [ 309.6724],
        [-302.1605]], grad_fn=<IndexBackward>) tensor([[ 294.1312],
        [-299.6739],
        [ 287.0066]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0682],
        [-0.0122],
        [ 0.6540]], grad_fn=<IndexBackward>)
complaint 7 assert approx

        [906.2983]], grad_fn=<IndexBackward>) tensor([[-299.3956],
        [-297.3365]], grad_fn=<IndexBackward>) tensor([[293.6870],
        [286.5767]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0105],
        [ 0.1096]], grad_fn=<IndexBackward>)
complaint 7 assert approx_eq: tensor([[ 32],
        [145]]) 
              1.. tensor([[-982.0763],
        [-895.4288]], grad_fn=<IndexBackward>) tensor([[987.7744],
        [906.2983]], grad_fn=<IndexBackward>) tensor([[-299.3956],
        [-297.3365]], grad_fn=<IndexBackward>) tensor([[293.6870],
        [286.5767]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0105],
        [ 0.1096]], grad_fn=<IndexBackward>)
yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
complaint 6 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-767.3843]], grad_fn=<IndexBackward>) tensor([[771.7927]], grad_fn=<IndexBackward>) tensor([[-266.6426]], grad_fn=<IndexBackward>) tensor([[262.1648]], grad_fn=<IndexBackward>) 
            

complaint -2420
yay -4040
complaint -2440
complaint -2460
complaint -2480
yay -4100
complaint -2500
complaint -2520
complaint -2540
yay -4160
complaint -2560
epoch 1400 loss = 1132.2261006037395; mean_loss= 1073.4304281670506; ()
mode_hat tensor(1.1120, requires_grad=True)
ltscale_hat tensor(-6.5097, requires_grad=True)
ldfraw_hat tensor(-1.4668, requires_grad=True)
complaint -2580
complaint -2600
yay -4220
complaint -2620
complaint -2640
complaint -2660
yay -4280
complaint -2680
complaint -2700
complaint -2720
yay -4340
complaint -2740
complaint -2760
complaint -2780
yay -4400
complaint -2800
complaint -2820
complaint -2840
yay -4460
complaint -2860
epoch 1500 loss = 1140.6264453530312; mean_loss= 1073.1328805845872; ()
mode_hat tensor(1.1324, requires_grad=True)
ltscale_hat tensor(-6.9530, requires_grad=True)
ldfraw_hat tensor(-1.4922, requires_grad=True)
Final mean_losses: 1073.1328805845872
guidename fully_amortized
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
gl

tensor([-4.5388, -4.4617], grad_fn=<SliceBackward>) (10 elems)
latentpsi:
tensor([-4.6052], requires_grad=True)
ldfraw_hat:
0.510834813117981
ltscale_hat:
-1.5666297674179077
mode_hat:
1.0562845468521118
1 1 ['unparametrized_laplace', 'fully_amortized']










1 1 ['unparametrized_laplace', 'fully_amortized'] [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu3.0.csv from file
400
tensor([-7.9208,  0.5222,  0.8593,  2.3906])
Sizes: torch.Size([400]) torch.Size([400])
guidename fully_amortized
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 10 40.0
yay 7 fix_m_grad
epoch 0 loss = 1056.615147471428; mean_loss= 1056.615147471428; ()
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(0.0050, requires_grad=True)
yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
complaint 9 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-767.6539]], gra

        [145]]) 
              1.. tensor([[-924.0392],
        [-874.7198]], grad_fn=<IndexBackward>) tensor([[948.9390],
        [892.7276]], grad_fn=<IndexBackward>) tensor([[-318.0920],
        [-305.8055]], grad_fn=<IndexBackward>) tensor([[293.2487],
        [286.1526]], grad_fn=<IndexBackward>) 
              2.. tensor([[ 0.0565],
        [-1.6451]], grad_fn=<IndexBackward>)
yay 1 fix_m_grad
complaint 6 assert approx_eq: tensor([[ 32],
        [145]]) 
              1.. tensor([[-925.1658],
        [-873.9899]], grad_fn=<IndexBackward>) tensor([[950.1849],
        [892.6880]], grad_fn=<IndexBackward>) tensor([[-317.1382],
        [-304.6594]], grad_fn=<IndexBackward>) tensor([[292.2919],
        [285.2224]], grad_fn=<IndexBackward>) 
              2.. tensor([[ 0.1729],
        [-0.7389]], grad_fn=<IndexBackward>)
complaint 5 assert approx_eq: tensor([[ 32],
        [145]]) 
              1.. tensor([[-927.0046],
        [-872.0675]], grad_fn=<IndexBackward>) tensor([[951.9190]

        [885.7507]], grad_fn=<IndexBackward>) tensor([[-310.8516],
        [-308.4438]], grad_fn=<IndexBackward>) tensor([[289.6209],
        [282.6371]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0258],
        [ 0.0876]], grad_fn=<IndexBackward>)
yay -20
complaint 4 assert approx_eq: tensor([[ 32],
        [145]]) 
              1.. tensor([[-947.6471],
        [-865.6367]], grad_fn=<IndexBackward>) tensor([[968.8929],
        [890.1700]], grad_fn=<IndexBackward>) tensor([[-310.1810],
        [-308.3380]], grad_fn=<IndexBackward>) tensor([[288.9152],
        [281.9518]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0200],
        [-1.8529]], grad_fn=<IndexBackward>)
complaint 3 assert approx_eq: tensor([[ 32],
        [145],
        [153]]) 
              1.. tensor([[-948.9473],
        [-866.5234],
        [-739.5901]], grad_fn=<IndexBackward>) tensor([[970.2617],
        [891.2322],
        [750.9979]], grad_fn=<IndexBackward>) tensor([[-309.5673],
       

              1.. tensor([[-868.9276]], grad_fn=<IndexBackward>) tensor([[892.8799]], grad_fn=<IndexBackward>) tensor([[-305.0917]], grad_fn=<IndexBackward>) tensor([[281.8798]], grad_fn=<IndexBackward>) 
              2.. tensor([[0.7404]], grad_fn=<IndexBackward>)
complaint 0
yay -80
complaint -20
yay -140
yay -200
yay -260
epoch 100 loss = 1158.1069669127464; mean_loss= 1136.392046246907; ()
mode_hat tensor(0.5026, requires_grad=True)
ltscale_hat tensor(-0.4928, requires_grad=True)
ldfraw_hat tensor(0.2653, requires_grad=True)
yay -320
complaint -40
yay -380
complaint -60
yay -440
complaint -80
yay -500
complaint -100
yay -560
epoch 200 loss = 1095.807698905468; mean_loss= 1114.5102142283822; ()
mode_hat tensor(0.9149, requires_grad=True)
ltscale_hat tensor(-0.9052, requires_grad=True)
ldfraw_hat tensor(0.2162, requires_grad=True)
yay -620
complaint -120
yay -680
complaint -140
yay -740
complaint -160
yay -800
complaint -180
yay -860
epoch 300 loss = 1065.3718531131744; mean_loss= 1

mode_hat tensor(1.1267, requires_grad=True)
ltscale_hat tensor(-3.1423, requires_grad=True)
ldfraw_hat tensor(-0.8094, requires_grad=True)
complaint -300
yay -2120
yay -2180
complaint -320
yay -2240
complaint -340
yay -2300
complaint -360
yay -2360
epoch 800 loss = 1071.7661891579628; mean_loss= 1089.1655048970513; ()
mode_hat tensor(1.1362, requires_grad=True)
ltscale_hat tensor(-3.6180, requires_grad=True)
ldfraw_hat tensor(-0.9684, requires_grad=True)
complaint -380
yay -2420
yay -2480
complaint -400
yay -2540
complaint -420
yay -2600
complaint -440
yay -2660
complaint -460
epoch 900 loss = 1089.8112194538116; mean_loss= 1088.6737032993935; ()
mode_hat tensor(1.1401, requires_grad=True)
ltscale_hat tensor(-4.0733, requires_grad=True)
ldfraw_hat tensor(-1.0689, requires_grad=True)
yay -2720
complaint -480
yay -2780
complaint -500
yay -2840
complaint -520
yay -2900
complaint -540
yay -2960
epoch 1000 loss = 1115.1673165559769; mean_loss= 1088.2596870463976; ()
mode_hat tensor(1.1417, 

        [153]]) 
              1.. tensor([[-863.1721],
        [-767.8949]], grad_fn=<IndexBackward>) tensor([[888.0262],
        [769.2001]], grad_fn=<IndexBackward>) tensor([[-308.2973],
        [-266.6116]], grad_fn=<IndexBackward>) tensor([[283.2878],
        [265.2805]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.1554],
        [-0.0260]], grad_fn=<IndexBackward>)
yay -20
complaint 1 assert approx_eq: tensor([[145],
        [153]]) 
              1.. tensor([[-867.9913],
        [-769.0180]], grad_fn=<IndexBackward>) tensor([[891.7834],
        [770.3697]], grad_fn=<IndexBackward>) tensor([[-308.3760],
        [-266.2340]], grad_fn=<IndexBackward>) tensor([[282.8874],
        [264.9146]], grad_fn=<IndexBackward>) 
              2.. tensor([[-1.6965],
        [ 0.0323]], grad_fn=<IndexBackward>)
complaint 0 assert approx_eq: tensor([[145]]) 
              1.. tensor([[-869.2064]], grad_fn=<IndexBackward>) tensor([[893.0709]], grad_fn=<IndexBackward>) tensor([[-308.022

        [ 261.0057]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0120],
        [-1.0410]], grad_fn=<IndexBackward>)
complaint 3 assert approx_eq: tensor([[ 40],
        [153]]) 
              1.. tensor([[ 974.4296],
        [-782.5385]], grad_fn=<IndexBackward>) tensor([[-989.3537],
        [ 784.8926]], grad_fn=<IndexBackward>) tensor([[ 298.8425],
        [-263.6364]], grad_fn=<IndexBackward>) tensor([[-283.9293],
        [ 260.7146]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0109],
        [-0.5678]], grad_fn=<IndexBackward>)
complaint 2 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-782.7380]], grad_fn=<IndexBackward>) tensor([[785.4507]], grad_fn=<IndexBackward>) tensor([[-263.2347]], grad_fn=<IndexBackward>) tensor([[260.4255]], grad_fn=<IndexBackward>) 
              2.. tensor([[-0.0966]], grad_fn=<IndexBackward>)
complaint 1 assert approx_eq: tensor([[153]]) 
              1.. tensor([[-782.9354]], grad_fn=<IndexBackward>) tensor([

1.1422489881515503
1 1 ['unparametrized_laplace', 'fully_amortized']










1 3 ['unparametrized_laplace', 'fully_amortized'] [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
1
testresults/scenario_N400_mu1.0_sigma2.0_nu3.0.csv from file
400
tensor([-7.9208,  0.5222,  0.8593,  2.3906])
Sizes: torch.Size([400]) torch.Size([400])
guidename unparametrized_laplace
sourceparams [{'modal_effect': 1.0, 'df': 3.0, 't_scale': 2.0}]
sizes torch.Size([400]) 400 100 4.0
yay 7 fix_m_grad
epoch 0 loss = 1241.752417663733; mean_loss= 1241.752417663733; ()
mode_hat tensor(0.0050, requires_grad=True)
ltscale_hat tensor(-0.0050, requires_grad=True)
ldfraw_hat tensor(-0.0050, requires_grad=True)
yay 4 fix_m_grad
yay 1 fix_m_grad
yay -20
yay -80
yay -140
complaint 9 assert approx_eq: tensor([[153],
        [199],
        [200]]) 
              1.. tensor([[-727.9871],
        [ 619.5005],
        [ 637.6830]], grad_fn=<IndexBackward>) tensor([[ 760.3495],
        [-620.1140],
        [-642.0941]], gr


\
MCMC, etc. 

In [3]:
print("running...")

import sys, os

print(sys.executable)
#print(sys.path)

from importlib import reload
import multisiteT #import *
reload(multisiteT)
from multisiteT import *
import cProfile as profile

print("making:")

multisiteMod = createScenario(tdom_fat_params)


running...
/anaconda3/bin/python
Reloading polytopize.
addHess tested
addHess tested
making:
1
testresults/scenario_N44_mu1.0_sigma2.0_nu-1.0.csv from file
44
tensor([32.5364, -3.3454,  3.2929, -2.5415])
{'hessian': tensor([[1., 0., 1.],
        [0., 2., 0.],
        [1., 0., 1.]]), 'logPosterior': 0}


In [13]:
multisiteMod.

SyntaxError: invalid syntax (<ipython-input-13-78d7c46ccca3>, line 1)

In [8]:
maxError = torch.max(errors)
print(float(maxError))

0.27889007329940796
